{
 "title": "Kuma CP",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "zone", "label": "Zone", "query": "label_values(cp_info, zone)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cp_info{zone=~\"$zone\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Live",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cp_info{instance=~\"$instance\"} OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Control Plane information",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "cp_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "graph",
   "description": "Only one instance should be a leader at a given point of time in every zone",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (zone, instance) (leader)",
     "legendFormat": "{{ zone }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Aggregated Discovery Service (XDS): CP-DP communication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "XDS message exchange",
   "type": "graph",
   "description": "Number of ADS messages exchanged between Control Plane and Dataplane over XDS",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xds_responses_sent{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Configuration sent"
    },
    {
     "expr": "sum(rate(xds_confirmation_received{confirmation=\"ACK\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Configuration accepted"
    },
    {
     "expr": "sum(rate(xds_confirmation_received{confirmation=\"NACK\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Configuration rejected"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=\"envoy.service.discovery.v2.AggregatedDiscoveryService\",grpc_code!=\"OK\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "RPC Errors"
    }
   ]
  },
  {
   "title": "XDS active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "xds_streams_active{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "XDS config generations",
   "type": "graph",
   "description": "Number of Envoy XDS config generations per second. Config is sent only when it's different than previously generated. The value should be the number of connected dataplanes * KUMA_XDS_SERVER_DATAPLANE_CONFIGURATION_REFRESH_INTERVAL",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xds_generation_count{instance=~\"$instance\"}[1m])) - sum(rate(xds_generation_errors{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(xds_generation_errors{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Latency of XDS config generation (99th percentile)",
   "type": "graph",
   "description": "How much it took to generate Envoy configuration for a single dataplane",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "xds_generation{quantile=\"0.99\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - Management of the Control Plane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Latency of API Server Requests (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (handler, le) (rate(api_server_http_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(api_server_http_request_duration_seconds_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Bootstrap Server - Initial configuration for Dataplane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Latency of Bootstrap Server Requests (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (handler, le) (rate(bootstrap_server_http_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(bootstrap_server_http_response_size_bytes_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Secret Discovery Service (SDS) - Certificates provider for Kuma DP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "SDS message exchange",
   "type": "graph",
   "description": "Number of SDS messages exchanged between Control Plane and Dataplane over SDS",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sds_responses_sent{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Configuration sent"
    },
    {
     "expr": "sum(rate(sds_confirmation_received{confirmation=\"ACK\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Configuration accepted"
    },
    {
     "expr": "sum(rate(sds_confirmation_received{confirmation=\"NACK\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Configuration rejected"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=\"envoy.service.discovery.v2.SecretDiscoveryService\",grpc_code!=\"OK\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "RPC Errors"
    }
   ]
  },
  {
   "title": "SDS active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sds_streams_active{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SDS config generations",
   "type": "graph",
   "description": "Number of Envoy SDS config generations per second. Config is sent only when it's different than previously generated. The value should be the number of connected dataplanes * KUMA_SDS_SERVER_DATAPLANE_CONFIGURATION_REFRESH_INTERVAL",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sds_generation_count{instance=~\"$instance\"}[1m])) - sum(rate(sds_generation_errors{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(sds_generation_errors{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Latency of SDS config generation (99th percentile)",
   "type": "graph",
   "description": "How much it took to generate SDS Envoy configuration for a single dataplane",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sds_generation{quantile=\"0.99\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Kuma Discovery Service (KDS) - Multicluster communication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Policies count (sync check)",
   "type": "graph",
   "description": "This metric presents if policies are properly propagated from Global to Remotes. All instances of global and remotes in the system should have the same number of policies. This metric have additional latency of 1 minute (it is not computed on the fly when scraping is done)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (zone, instance) (resources_count{instance=~\"$instance\",resource_type!~\"Dataplane|DataplaneInsight|Zone|ZoneInsight\"})",
     "legendFormat": "{{ zone }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Dataplane count",
   "type": "graph",
   "description": "This metric presents if Dataplanes are properly propagated from Remotes to Global. Keep in mind that Dataplanes from all remotes != Dataplanes from global. All remotes receive additional one dataplane of Ingress from other Remotes. This metric have additional latency of 1 minute (it is not computed on the fly when scraping is done)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (zone, instance) (resources_count{instance=~\"$instance\",resource_type=\"Dataplane\"})",
     "legendFormat": "{{ zone }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Global - KDS message exchange",
   "type": "graph",
   "description": "Number of KDS messages exchanged between Global Control Plane and Remote Control Plane over KDS. Global sends to Remote policies and Ingress Dataplanes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kds_responses_sent{instance=~\"$instance\",zone=\"Global\"}[1m]))",
     "legendFormat": "Configuration sent"
    },
    {
     "expr": "sum(rate(kds_confirmation_received{confirmation=\"NACK\",instance=~\"$instance\",zone=\"Global\"}[1m]))",
     "legendFormat": "Configuration rejected"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=\"kuma.mesh.v1alpha1.MultiplexService\",grpc_code!=\"OK\",instance=~\"$instance\",zone=\"Global\"}[1m]))",
     "legendFormat": "RPC Errors"
    }
   ]
  },
  {
   "title": "Global - KDS active connections",
   "type": "graph",
   "description": "Number of remote CP connected to Global.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kds_streams_active{instance=~\"$instance\",zone=\"Global\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Global - KDS config generations",
   "type": "graph",
   "description": "Number of KDS config generations per second. Config is sent only when it's different than previously generated. The value should be the number of connected control planes * KUMA_MULTICLUSTER_GLOBAL_KDS_REFRESH_INTERVAL",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kds_generation_count{instance=~\"$instance\",zone=\"Global\"}[1m])) - sum(rate(kds_generation_errors{instance=~\"$instance\",zone=\"Global\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(kds_generation_errors{instance=~\"$instance\",zone=\"Global\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Global - Latency of KDS config generation (99th percentile)",
   "type": "graph",
   "description": "How much it took to generate KDS configuration for a single remote control plane",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kds_generation{quantile=\"0.99\",instance=~\"$instance\",zone=\"Global\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Remote - KDS message exchange",
   "type": "graph",
   "description": "Number of KDS messages exchanged between Global Control Plane and Remote Control Plane over KDS. Remote sends to Global its Dataplanes and DataplaneInsights",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kds_responses_sent{instance=~\"$instance\",zone!=\"Global\"}[1m]))",
     "legendFormat": "Configuration sent"
    },
    {
     "expr": "sum(rate(kds_confirmation_received{confirmation=\"NACK\",instance=~\"$instance\",zone!=\"Global\"}[1m]))",
     "legendFormat": "Configuration rejected"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=\"kuma.mesh.v1alpha1.MultiplexService\",grpc_code!=\"OK\",instance=~\"$instance\",zone!=\"Global\"}[1m]))",
     "legendFormat": "RPC Errors"
    }
   ]
  },
  {
   "title": "Remote - KDS active connections",
   "type": "graph",
   "description": "Number of global CP connected to Remote.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kds_streams_active{instance=~\"$instance\",zone!=\"Global\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Remote - KDS config generations",
   "type": "graph",
   "description": "Number of KDS config generations per second. Config is sent only when it's different than previously generated. The value should be the number of connected control planes * KUMA_MULTICLUSTER_REMOTE_KDS_REFRESH_INTERVAL",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kds_generation_count{instance=~\"$instance\",zone!=\"Global\"}[1m])) - sum(rate(kds_generation_errors{instance=~\"$instance\",zone!=\"Global\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(kds_generation_errors{instance=~\"$instance\",zone!=\"Global\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Remote - Latency of KDS config generation (99th percentile)",
   "type": "graph",
   "description": "How much it took to generate KDS configuration for a global control plane",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kds_generation{quantile=\"0.99\",instance=~\"$instance\",zone!=\"Global\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Admin Server - Administrative management of the Control Plane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "Latency of Admin Server Requests (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (handler, le) (rate(admin_server_http_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(admin_server_http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "DNS Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Latency of DNS response (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "dns_server{quantile=\"0.99\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DNS responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dns_server_resolution{instance=~\"$instance\",result=\"resolved\"}[1m]))",
     "legendFormat": "Resolved"
    },
    {
     "expr": "sum(rate(dns_server_resolution{instance=~\"$instance\",result=\"unresolved\"}[1m]))",
     "legendFormat": "Unresolved"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Latency of Store operations (99th percentile)",
   "type": "graph",
   "description": "Latency of underlying storage (API Server on K8S, Postgres on Universal etc.)",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(store_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Store cache performance",
   "type": "graph",
   "description": "Cache protects underlying storage by sharing responses between many goroutines accessing the storage.\n\nhit - request was retrieved from the cache.\n\nhit-wait - request was retrieved from the cache after waiting for a concurrent request to fetch it from the database.\n\nmiss - request was fetched from the database\n\nRefer to https://kuma.io/docs/latest/documentation/fine-tuning/#snapshot-generation",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 92 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(store_cache{result=\"hit\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(rate(store_cache{result=\"hit-wait\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Hit Wait"
    },
    {
     "expr": "sum(rate(store_cache{result=\"miss\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Store operations",
   "type": "graph",
   "description": "Real requests executed on the underlying storage (Postgres/Kubernetes API Server)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (operation, resource_type) (rate(store_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{operation}} - {{resource_type}}"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Latency of GC time (75th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 102 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\", quantile=\"0.75\"}",
     "legendFormat": "{{ instance}}"
    }
   ]
  }
 ]
}