// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/config/app/kumactl/v1alpha1/config.proto

package v1alpha1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration defines configuration of `kumactl`.
type Configuration struct {
	// List of known Control Planes.
	ControlPlanes []*ControlPlane `protobuf:"bytes,1,rep,name=control_planes,json=controlPlanes,proto3" json:"control_planes,omitempty"`
	// List of configured `kumactl` contexts.
	Contexts []*Context `protobuf:"bytes,2,rep,name=contexts,proto3" json:"contexts,omitempty"`
	// Name of the context to use by default.
	CurrentContext       string   `protobuf:"bytes,3,opt,name=current_context,json=currentContext,proto3" json:"current_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_18c2b02c7dd453f4, []int{0}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetControlPlanes() []*ControlPlane {
	if m != nil {
		return m.ControlPlanes
	}
	return nil
}

func (m *Configuration) GetContexts() []*Context {
	if m != nil {
		return m.Contexts
	}
	return nil
}

func (m *Configuration) GetCurrentContext() string {
	if m != nil {
		return m.CurrentContext
	}
	return ""
}

// ControlPlane defines a Control Plane.
type ControlPlane struct {
	// Name defines a reference name for a given Control Plane.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Coordinates defines coordinates of a given Control Plane.
	Coordinates          *ControlPlaneCoordinates `protobuf:"bytes,2,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ControlPlane) Reset()         { *m = ControlPlane{} }
func (m *ControlPlane) String() string { return proto.CompactTextString(m) }
func (*ControlPlane) ProtoMessage()    {}
func (*ControlPlane) Descriptor() ([]byte, []int) {
	return fileDescriptor_18c2b02c7dd453f4, []int{1}
}

func (m *ControlPlane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlPlane.Unmarshal(m, b)
}
func (m *ControlPlane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlPlane.Marshal(b, m, deterministic)
}
func (m *ControlPlane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlPlane.Merge(m, src)
}
func (m *ControlPlane) XXX_Size() int {
	return xxx_messageInfo_ControlPlane.Size(m)
}
func (m *ControlPlane) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlPlane.DiscardUnknown(m)
}

var xxx_messageInfo_ControlPlane proto.InternalMessageInfo

func (m *ControlPlane) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ControlPlane) GetCoordinates() *ControlPlaneCoordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

// ControlPlaneCoordinates defines coordinates of a Control Plane.
type ControlPlaneCoordinates struct {
	ApiServer            *ControlPlaneCoordinates_ApiServer `protobuf:"bytes,1,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ControlPlaneCoordinates) Reset()         { *m = ControlPlaneCoordinates{} }
func (m *ControlPlaneCoordinates) String() string { return proto.CompactTextString(m) }
func (*ControlPlaneCoordinates) ProtoMessage()    {}
func (*ControlPlaneCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_18c2b02c7dd453f4, []int{2}
}

func (m *ControlPlaneCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlPlaneCoordinates.Unmarshal(m, b)
}
func (m *ControlPlaneCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlPlaneCoordinates.Marshal(b, m, deterministic)
}
func (m *ControlPlaneCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlPlaneCoordinates.Merge(m, src)
}
func (m *ControlPlaneCoordinates) XXX_Size() int {
	return xxx_messageInfo_ControlPlaneCoordinates.Size(m)
}
func (m *ControlPlaneCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlPlaneCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_ControlPlaneCoordinates proto.InternalMessageInfo

func (m *ControlPlaneCoordinates) GetApiServer() *ControlPlaneCoordinates_ApiServer {
	if m != nil {
		return m.ApiServer
	}
	return nil
}

type ControlPlaneCoordinates_ApiServer struct {
	// URL defines URL of the Control Plane API Server.
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlPlaneCoordinates_ApiServer) Reset()         { *m = ControlPlaneCoordinates_ApiServer{} }
func (m *ControlPlaneCoordinates_ApiServer) String() string { return proto.CompactTextString(m) }
func (*ControlPlaneCoordinates_ApiServer) ProtoMessage()    {}
func (*ControlPlaneCoordinates_ApiServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_18c2b02c7dd453f4, []int{2, 0}
}

func (m *ControlPlaneCoordinates_ApiServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlPlaneCoordinates_ApiServer.Unmarshal(m, b)
}
func (m *ControlPlaneCoordinates_ApiServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlPlaneCoordinates_ApiServer.Marshal(b, m, deterministic)
}
func (m *ControlPlaneCoordinates_ApiServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlPlaneCoordinates_ApiServer.Merge(m, src)
}
func (m *ControlPlaneCoordinates_ApiServer) XXX_Size() int {
	return xxx_messageInfo_ControlPlaneCoordinates_ApiServer.Size(m)
}
func (m *ControlPlaneCoordinates_ApiServer) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlPlaneCoordinates_ApiServer.DiscardUnknown(m)
}

var xxx_messageInfo_ControlPlaneCoordinates_ApiServer proto.InternalMessageInfo

func (m *ControlPlaneCoordinates_ApiServer) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// Context defines a context in which individual `kumactl` commands run.
type Context struct {
	// Name defines a reference name for a given context.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ControlPlane defines a reference to a known Control Plane.
	ControlPlane string `protobuf:"bytes,2,opt,name=control_plane,json=controlPlane,proto3" json:"control_plane,omitempty"`
	// Defaults defines default settings for a given context.
	Defaults             *Context_Defaults    `protobuf:"bytes,3,opt,name=defaults,proto3" json:"defaults,omitempty"`
	Credentials          *Context_Credentials `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_18c2b02c7dd453f4, []int{3}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Context) GetControlPlane() string {
	if m != nil {
		return m.ControlPlane
	}
	return ""
}

func (m *Context) GetDefaults() *Context_Defaults {
	if m != nil {
		return m.Defaults
	}
	return nil
}

func (m *Context) GetCredentials() *Context_Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

// Defaults defines default settings for a context.
type Context_Defaults struct {
	// Mesh defines a Mesh to use in requests if one is not provided explicitly.
	Mesh                 string   `protobuf:"bytes,1,opt,name=mesh,proto3" json:"mesh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context_Defaults) Reset()         { *m = Context_Defaults{} }
func (m *Context_Defaults) String() string { return proto.CompactTextString(m) }
func (*Context_Defaults) ProtoMessage()    {}
func (*Context_Defaults) Descriptor() ([]byte, []int) {
	return fileDescriptor_18c2b02c7dd453f4, []int{3, 0}
}

func (m *Context_Defaults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_Defaults.Unmarshal(m, b)
}
func (m *Context_Defaults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_Defaults.Marshal(b, m, deterministic)
}
func (m *Context_Defaults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_Defaults.Merge(m, src)
}
func (m *Context_Defaults) XXX_Size() int {
	return xxx_messageInfo_Context_Defaults.Size(m)
}
func (m *Context_Defaults) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_Defaults.DiscardUnknown(m)
}

var xxx_messageInfo_Context_Defaults proto.InternalMessageInfo

func (m *Context_Defaults) GetMesh() string {
	if m != nil {
		return m.Mesh
	}
	return ""
}

// Credentials defines credentials for various APIs
type Context_Credentials struct {
	// AdminApiCredentials defines credentials for admin client
	AdminApi             *Context_AdminApiCredentials `protobuf:"bytes,1,opt,name=adminApi,proto3" json:"adminApi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Context_Credentials) Reset()         { *m = Context_Credentials{} }
func (m *Context_Credentials) String() string { return proto.CompactTextString(m) }
func (*Context_Credentials) ProtoMessage()    {}
func (*Context_Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_18c2b02c7dd453f4, []int{3, 1}
}

func (m *Context_Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_Credentials.Unmarshal(m, b)
}
func (m *Context_Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_Credentials.Marshal(b, m, deterministic)
}
func (m *Context_Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_Credentials.Merge(m, src)
}
func (m *Context_Credentials) XXX_Size() int {
	return xxx_messageInfo_Context_Credentials.Size(m)
}
func (m *Context_Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Context_Credentials proto.InternalMessageInfo

func (m *Context_Credentials) GetAdminApi() *Context_AdminApiCredentials {
	if m != nil {
		return m.AdminApi
	}
	return nil
}

// AdminApiCredentials defines credential configuration of admin client
type Context_AdminApiCredentials struct {
	// ClientCert defines certificate of authorized client of admin server
	ClientCert string `protobuf:"bytes,2,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty"`
	// ClientKey defines key of authorized client of admin server
	ClientKey            string   `protobuf:"bytes,3,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context_AdminApiCredentials) Reset()         { *m = Context_AdminApiCredentials{} }
func (m *Context_AdminApiCredentials) String() string { return proto.CompactTextString(m) }
func (*Context_AdminApiCredentials) ProtoMessage()    {}
func (*Context_AdminApiCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_18c2b02c7dd453f4, []int{3, 2}
}

func (m *Context_AdminApiCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_AdminApiCredentials.Unmarshal(m, b)
}
func (m *Context_AdminApiCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_AdminApiCredentials.Marshal(b, m, deterministic)
}
func (m *Context_AdminApiCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_AdminApiCredentials.Merge(m, src)
}
func (m *Context_AdminApiCredentials) XXX_Size() int {
	return xxx_messageInfo_Context_AdminApiCredentials.Size(m)
}
func (m *Context_AdminApiCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_AdminApiCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_Context_AdminApiCredentials proto.InternalMessageInfo

func (m *Context_AdminApiCredentials) GetClientCert() string {
	if m != nil {
		return m.ClientCert
	}
	return ""
}

func (m *Context_AdminApiCredentials) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Configuration)(nil), "kumactl.config.v1alpha1.Configuration")
	proto.RegisterType((*ControlPlane)(nil), "kumactl.config.v1alpha1.ControlPlane")
	proto.RegisterType((*ControlPlaneCoordinates)(nil), "kumactl.config.v1alpha1.ControlPlaneCoordinates")
	proto.RegisterType((*ControlPlaneCoordinates_ApiServer)(nil), "kumactl.config.v1alpha1.ControlPlaneCoordinates.ApiServer")
	proto.RegisterType((*Context)(nil), "kumactl.config.v1alpha1.Context")
	proto.RegisterType((*Context_Defaults)(nil), "kumactl.config.v1alpha1.Context.Defaults")
	proto.RegisterType((*Context_Credentials)(nil), "kumactl.config.v1alpha1.Context.Credentials")
	proto.RegisterType((*Context_AdminApiCredentials)(nil), "kumactl.config.v1alpha1.Context.AdminApiCredentials")
}

func init() {
	proto.RegisterFile("pkg/config/app/kumactl/v1alpha1/config.proto", fileDescriptor_18c2b02c7dd453f4)
}

var fileDescriptor_18c2b02c7dd453f4 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x8e, 0xd3, 0x3c,
	0x14, 0x95, 0x27, 0xfd, 0x3e, 0x92, 0x9b, 0xe9, 0x80, 0xcc, 0xa2, 0x51, 0xc4, 0x4f, 0x55, 0x09,
	0xd1, 0x91, 0x46, 0x09, 0x53, 0x58, 0x21, 0x36, 0x6d, 0x60, 0x05, 0x42, 0xa3, 0x20, 0x36, 0x2c,
	0x88, 0x4c, 0x72, 0x67, 0xc6, 0x6a, 0x9a, 0x58, 0x8e, 0x53, 0xcd, 0xbc, 0x01, 0x42, 0xe2, 0x49,
	0x78, 0x03, 0x56, 0x2c, 0x90, 0x78, 0x16, 0xde, 0x02, 0xc5, 0x71, 0x3a, 0xa9, 0xc4, 0x50, 0xd8,
	0xd9, 0xc7, 0xe7, 0x1c, 0x1f, 0xdf, 0x7b, 0x0d, 0x47, 0x62, 0x79, 0x16, 0xa6, 0x65, 0x71, 0xca,
	0xcf, 0x42, 0x26, 0x44, 0xb8, 0xac, 0x57, 0x2c, 0x55, 0x79, 0xb8, 0x3e, 0x66, 0xb9, 0x38, 0x67,
	0xc7, 0xe6, 0x2c, 0x10, 0xb2, 0x54, 0x25, 0x1d, 0x99, 0xe3, 0xc0, 0xa0, 0x1d, 0xcb, 0x1f, 0xad,
	0x59, 0xce, 0x33, 0xa6, 0x30, 0xec, 0x16, 0xad, 0x62, 0xf2, 0x9d, 0xc0, 0x30, 0xd2, 0xe4, 0x5a,
	0x32, 0xc5, 0xcb, 0x82, 0xbe, 0x82, 0x83, 0xb4, 0x2c, 0x94, 0x2c, 0xf3, 0x44, 0xe4, 0xac, 0xc0,
	0xca, 0x23, 0x63, 0x6b, 0xea, 0xce, 0x1e, 0x04, 0xd7, 0x98, 0x07, 0x51, 0x4b, 0x3f, 0x69, 0xd8,
	0xf1, 0x30, 0xed, 0xed, 0x2a, 0xfa, 0x0c, 0xec, 0x06, 0xc0, 0x0b, 0x55, 0x79, 0x7b, 0xda, 0x67,
	0xfc, 0x47, 0x1f, 0xbc, 0x50, 0xf1, 0x46, 0x41, 0x1f, 0xc2, 0xcd, 0xb4, 0x96, 0x12, 0x0b, 0x95,
	0x18, 0xcc, 0xb3, 0xc6, 0x64, 0xea, 0xc4, 0x07, 0x06, 0x36, 0x92, 0xc9, 0x67, 0x02, 0xfb, 0xfd,
	0x18, 0xf4, 0x2e, 0x0c, 0x0a, 0xb6, 0x42, 0x8f, 0x34, 0xf4, 0x85, 0xf3, 0xf5, 0xe7, 0x37, 0x6b,
	0x20, 0xf7, 0x6e, 0x91, 0x58, 0xc3, 0xf4, 0x3d, 0xb8, 0x69, 0x59, 0xca, 0x8c, 0x17, 0x4c, 0x61,
	0x93, 0x8c, 0x4c, 0xdd, 0xd9, 0xa3, 0xbf, 0x7a, 0x61, 0x74, 0xa5, 0x5b, 0x40, 0xe3, 0xfb, 0xdf,
	0x27, 0xd2, 0x18, 0xf7, 0x0d, 0x27, 0x5f, 0x08, 0x8c, 0xae, 0x11, 0x51, 0x04, 0x60, 0x82, 0x27,
	0x15, 0xca, 0x35, 0x4a, 0x1d, 0xd0, 0x9d, 0x3d, 0xfd, 0xd7, 0xab, 0x83, 0xb9, 0xe0, 0x6f, 0xb4,
	0xc3, 0x56, 0x08, 0x87, 0x75, 0xb0, 0x7f, 0x08, 0xce, 0x86, 0x43, 0xef, 0x80, 0x55, 0xcb, 0xdc,
	0x54, 0xa3, 0x15, 0x48, 0xeb, 0x23, 0x21, 0x71, 0x03, 0x4f, 0x7e, 0x58, 0x70, 0xc3, 0x54, 0x72,
	0x57, 0xe1, 0x02, 0x18, 0x6e, 0x4d, 0x87, 0x2e, 0xdd, 0x16, 0x6f, 0xbf, 0x3f, 0x00, 0xf4, 0x05,
	0xd8, 0x19, 0x9e, 0xb2, 0x3a, 0x57, 0x95, 0x6e, 0x9d, 0x3b, 0x3b, 0xdc, 0xd5, 0xff, 0xe0, 0xb9,
	0x11, 0xc4, 0x1b, 0x29, 0x7d, 0x0d, 0x6e, 0x2a, 0x31, 0xc3, 0x42, 0x71, 0x96, 0x57, 0xde, 0x40,
	0x3b, 0x1d, 0xed, 0x74, 0x8a, 0xae, 0x34, 0x71, 0xdf, 0xc0, 0xbf, 0x07, 0x76, 0x77, 0x0b, 0xa5,
	0x30, 0x58, 0x61, 0x75, 0xde, 0xbe, 0x38, 0xd6, 0x6b, 0x3f, 0x01, 0xb7, 0xa7, 0xa5, 0x27, 0x60,
	0xb3, 0x6c, 0xc5, 0x8b, 0xb9, 0xe0, 0xa6, 0x61, 0x4f, 0x76, 0xde, 0x3d, 0x37, 0x82, 0x7e, 0x86,
	0x8d, 0x8b, 0xff, 0x16, 0x6e, 0xff, 0x86, 0x40, 0xef, 0x83, 0x9b, 0xe6, 0x5c, 0xcf, 0x3b, 0x4a,
	0xd5, 0x16, 0x37, 0x86, 0x16, 0x8a, 0x50, 0x36, 0xed, 0x31, 0xbb, 0x64, 0x89, 0x97, 0xe6, 0x33,
	0x38, 0x2d, 0xf2, 0x12, 0x2f, 0x17, 0xf0, 0xce, 0xee, 0x82, 0x7c, 0xf8, 0x5f, 0xff, 0xf0, 0xc7,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xca, 0x91, 0x5d, 0xc0, 0x43, 0x04, 0x00, 0x00,
}
