// Generated by tools/policy-gen. DO NOT EDIT.
// Run "make generate" to update this file.

package v1alpha1

import (
	common_api "github.com/kumahq/kuma/v3/api/common/v1alpha1"
	core_model "github.com/kumahq/kuma/v3/pkg/core/resources/model"
	"github.com/kumahq/kuma/v3/pkg/util/pointer"
)

func (x *DoNothingPolicy) GetTargetRef() common_api.TargetRef {
	return x.TargetRef.ToTargetRef()
}

func (x *From) GetTargetRef() common_api.TargetRef {
	return x.TargetRef
}

func (x *From) GetDefault() interface{} {
	return x.Default
}

func (x *DoNothingPolicy) GetFromList() []core_model.PolicyItem {
	var result []core_model.PolicyItem
	for _, itm := range pointer.Deref(x.From) {
		item := itm
		result = append(result, &item)
	}
	return result
}

func (x *To) GetTargetRef() common_api.TargetRef {
	return x.TargetRef.ToTargetRef()
}

func (x *To) GetDefault() interface{} {
	return x.Default
}

func (x *DoNothingPolicy) GetToList() []core_model.PolicyItem {
	var result []core_model.PolicyItem
	for _, itm := range pointer.Deref(x.To) {
		item := itm
		result = append(result, &item)
	}
	return result
}
