// Generated by tools/policy-gen. DO NOT EDIT.
// Run "make generate" to update this file.

package v1alpha1

import (
	"encoding/json"
	"errors"
	"fmt"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	policy "github.com/kumahq/kuma/v3/pkg/core/resources/apis/zoneinsight/api/v1alpha1"
	core_model "github.com/kumahq/kuma/v3/pkg/core/resources/model"
	"github.com/kumahq/kuma/v3/pkg/plugins/resources/k8s/native/pkg/model"
	"github.com/kumahq/kuma/v3/pkg/plugins/resources/k8s/native/pkg/registry"
)

// ZoneInsight defines the observed state of a Zone Kuma CP.
// EnvoyAdminStreams is deprecated, KDSStreams replaces it.
// +kubebuilder:object:root=true
// +kubebuilder:resource:categories=kuma,scope=Cluster,shortName=
type ZoneInsight struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec is the specification of the Kuma ZoneInsight resource.
	// +kubebuilder:validation:Optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Spec *apiextensionsv1.JSON `json:"spec,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Cluster
type ZoneInsightList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZoneInsight `json:"items"`
}

func (cb *ZoneInsight) GetObjectMeta() *metav1.ObjectMeta {
	return &cb.ObjectMeta
}

func (cb *ZoneInsight) SetObjectMeta(m *metav1.ObjectMeta) {
	cb.ObjectMeta = *m
}

func (cb *ZoneInsight) GetMesh() string {
	// ZoneInsight is a Global-scoped resource and is not bound to a mesh.
	return ""
}

func (cb *ZoneInsight) SetMesh(mesh string) {
	// ZoneInsight is a Global-scoped resource, the mesh label must not be set.
}
func (cb *ZoneInsight) GetSpec() (core_model.ResourceSpec, error) {
	spec := cb.Spec
	if spec == nil || len(spec.Raw) == 0 {
		return &policy.ZoneInsight{}, nil
	}
	out := &policy.ZoneInsight{}
	if err := json.Unmarshal(spec.Raw, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (cb *ZoneInsight) SetSpec(spec core_model.ResourceSpec) {
	if spec == nil {
		cb.Spec = nil
		return
	}

	if _, ok := spec.(*policy.ZoneInsight); !ok {
		panic(fmt.Sprintf("unexpected type %T", spec))
	}

	raw, err := json.Marshal(spec)
	if err != nil {
		panic(err)
	}
	cb.Spec = &apiextensionsv1.JSON{Raw: raw}
}

func (cb *ZoneInsight) GetStatus() (core_model.ResourceStatus, error) {
	return nil, nil
}

func (cb *ZoneInsight) SetStatus(status core_model.ResourceStatus) error {
	return errors.New("status not supported")
}

func (cb *ZoneInsight) Scope() model.Scope {
	return model.ScopeCluster
}

func (l *ZoneInsightList) GetItems() []model.KubernetesObject {
	result := make([]model.KubernetesObject, len(l.Items))
	for i := range l.Items {
		result[i] = &l.Items[i]
	}
	return result
}

func init() {
	knownTypes = append(knownTypes, &ZoneInsight{}, &ZoneInsightList{})
	registry.RegisterObjectType(&policy.ZoneInsight{}, &ZoneInsight{
		TypeMeta: metav1.TypeMeta{
			APIVersion: GroupVersion.String(),
			Kind:       "ZoneInsight",
		},
	})
	registry.RegisterListType(&policy.ZoneInsight{}, &ZoneInsightList{
		TypeMeta: metav1.TypeMeta{
			APIVersion: GroupVersion.String(),
			Kind:       "ZoneInsightList",
		},
	})
}
