// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.20.0
// source: api/system/v1alpha1/config.proto

package v1alpha1

import (
	_ "github.com/kumahq/kuma/api/mesh"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is a entity that represents dynamic configuration that is stored in
// underlying storage. For now it's used only for internal mechanisms.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// configuration that is stored (ex. in JSON)
	Config        string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_api_system_v1alpha1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1alpha1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_api_system_v1alpha1_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

var File_api_system_v1alpha1_config_proto protoreflect.FileDescriptor

const file_api_system_v1alpha1_config_proto_rawDesc = "" +
	"\n" +
	" api/system/v1alpha1/config.proto\x12\x14kuma.system.v1alpha1\x1a\x16api/mesh/options.proto\"\x80\x01\n" +
	"\x06Config\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config:^\xaa\x8c\x89\xa6\x01X\n" +
	"\x0eConfigResource\x12\x06Config\x18\x01\"\x06systemR2model.GlobalToZonesFlag | model.ProvidedByZoneFlag`\x01B,Z*github.com/kumahq/kuma/api/system/v1alpha1b\x06proto3"

var (
	file_api_system_v1alpha1_config_proto_rawDescOnce sync.Once
	file_api_system_v1alpha1_config_proto_rawDescData []byte
)

func file_api_system_v1alpha1_config_proto_rawDescGZIP() []byte {
	file_api_system_v1alpha1_config_proto_rawDescOnce.Do(func() {
		file_api_system_v1alpha1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_system_v1alpha1_config_proto_rawDesc), len(file_api_system_v1alpha1_config_proto_rawDesc)))
	})
	return file_api_system_v1alpha1_config_proto_rawDescData
}

var file_api_system_v1alpha1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_system_v1alpha1_config_proto_goTypes = []any{
	(*Config)(nil), // 0: kuma.system.v1alpha1.Config
}
var file_api_system_v1alpha1_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_system_v1alpha1_config_proto_init() }
func file_api_system_v1alpha1_config_proto_init() {
	if File_api_system_v1alpha1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_system_v1alpha1_config_proto_rawDesc), len(file_api_system_v1alpha1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_system_v1alpha1_config_proto_goTypes,
		DependencyIndexes: file_api_system_v1alpha1_config_proto_depIdxs,
		MessageInfos:      file_api_system_v1alpha1_config_proto_msgTypes,
	}.Build()
	File_api_system_v1alpha1_config_proto = out.File
	file_api_system_v1alpha1_config_proto_goTypes = nil
	file_api_system_v1alpha1_config_proto_depIdxs = nil
}
