// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.20.0
// source: api/system/v1alpha1/secret.proto

package v1alpha1

import (
	_ "github.com/kumahq/kuma/api/mesh"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Secret defines an encrypted value in Kuma.
type Secret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value of the secret
	Data          *wrapperspb.BytesValue `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_api_system_v1alpha1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1alpha1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_api_system_v1alpha1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetData() *wrapperspb.BytesValue {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_system_v1alpha1_secret_proto protoreflect.FileDescriptor

const file_api_system_v1alpha1_secret_proto_rawDesc = "" +
	"\n" +
	" api/system/v1alpha1/secret.proto\x12\x14kuma.system.v1alpha1\x1a\x16api/mesh/options.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa3\x01\n" +
	"\x06Secret\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.google.protobuf.BytesValueR\x04data:h\xaa\x8c\x89\xa6\x01b\n" +
	"\x0eSecretResource\x12\x06Secret\"\x06system:\n" +
	"\n" +
	"\x06secret \x01R2model.GlobalToZonesFlag | model.ProvidedByZoneFlag`\x01B,Z*github.com/kumahq/kuma/api/system/v1alpha1b\x06proto3"

var (
	file_api_system_v1alpha1_secret_proto_rawDescOnce sync.Once
	file_api_system_v1alpha1_secret_proto_rawDescData []byte
)

func file_api_system_v1alpha1_secret_proto_rawDescGZIP() []byte {
	file_api_system_v1alpha1_secret_proto_rawDescOnce.Do(func() {
		file_api_system_v1alpha1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_system_v1alpha1_secret_proto_rawDesc), len(file_api_system_v1alpha1_secret_proto_rawDesc)))
	})
	return file_api_system_v1alpha1_secret_proto_rawDescData
}

var file_api_system_v1alpha1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_system_v1alpha1_secret_proto_goTypes = []any{
	(*Secret)(nil),                // 0: kuma.system.v1alpha1.Secret
	(*wrapperspb.BytesValue)(nil), // 1: google.protobuf.BytesValue
}
var file_api_system_v1alpha1_secret_proto_depIdxs = []int32{
	1, // 0: kuma.system.v1alpha1.Secret.data:type_name -> google.protobuf.BytesValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_system_v1alpha1_secret_proto_init() }
func file_api_system_v1alpha1_secret_proto_init() {
	if File_api_system_v1alpha1_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_system_v1alpha1_secret_proto_rawDesc), len(file_api_system_v1alpha1_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_system_v1alpha1_secret_proto_goTypes,
		DependencyIndexes: file_api_system_v1alpha1_secret_proto_depIdxs,
		MessageInfos:      file_api_system_v1alpha1_secret_proto_msgTypes,
	}.Build()
	File_api_system_v1alpha1_secret_proto = out.File
	file_api_system_v1alpha1_secret_proto_goTypes = nil
	file_api_system_v1alpha1_secret_proto_depIdxs = nil
}
