{{- $ingress := .Values.controlPlane.ingress | default dict }}
{{- if $ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kuma.controlPlane.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "kuma.cpLabels" . | nindent 4 }}
spec:
  ingressClassName: {{ $ingress.ingressClassName }}
  rules:
  - host: {{ $ingress.hostname }}
    http:
      paths:
      - path: {{ $ingress.path }}
        pathType: {{ $ingress.pathType }}
        backend:
          service:
            name: {{ include "kuma.controlPlane.serviceName" . }}
            port:
              number: {{ $ingress.servicePort }}
{{- end }}
