{{- if .Values.ingress.autoscaling.enabled }}
apiVersion: "autoscaling/v2"
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kuma.name" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kuma.ingressLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kuma.name" . }}-ingress
  minReplicas: {{ .Values.ingress.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ingress.autoscaling.maxReplicas }}
  metrics: {{- toYaml .Values.ingress.autoscaling.metrics | nindent 4 }}
{{- end }}
