{{- range $meshEntry := .Values.meshes }}
{{- $meshName := $meshEntry.name }}

{{- if and $meshEntry.ingress $meshEntry.ingress.enabled $meshEntry.ingress.pdb $meshEntry.ingress.pdb.enabled }}
{{- $role := "ingress" }}
{{- $cfg := $meshEntry.ingress.pdb }}
---
{{ if $.Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{ else if $.Capabilities.APIVersions.Has "policy/v1beta1" }}
apiVersion: policy/v1beta1
{{ else }}
{{ fail "pod disruption budgets are not supported by this version of kubernetes" }}
{{ end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "kuma.mesh.zoneproxy.name" (dict "root" $ "meshName" $meshName "role" $role) }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "kuma.mesh.zoneproxy.labels" (dict "root" $ "meshName" $meshName "role" $role) | nindent 4 }}
spec:
  maxUnavailable: {{ default 1 $cfg.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "kuma.mesh.zoneproxy.selectorLabels" (dict "root" $ "meshName" $meshName "role" $role) | nindent 6 }}
{{- end }}

{{- if and $meshEntry.egress $meshEntry.egress.enabled $meshEntry.egress.pdb $meshEntry.egress.pdb.enabled }}
{{- $role := "egress" }}
{{- $cfg := $meshEntry.egress.pdb }}
---
{{ if $.Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{ else if $.Capabilities.APIVersions.Has "policy/v1beta1" }}
apiVersion: policy/v1beta1
{{ else }}
{{ fail "pod disruption budgets are not supported by this version of kubernetes" }}
{{ end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "kuma.mesh.zoneproxy.name" (dict "root" $ "meshName" $meshName "role" $role) }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "kuma.mesh.zoneproxy.labels" (dict "root" $ "meshName" $meshName "role" $role) | nindent 4 }}
spec:
  maxUnavailable: {{ default 1 $cfg.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "kuma.mesh.zoneproxy.selectorLabels" (dict "root" $ "meshName" $meshName "role" $role) | nindent 6 }}
{{- end }}

{{- end }}
