{{- range $meshEntry := .Values.meshes }}
{{- $meshName := $meshEntry.name }}

{{- if and $meshEntry.ingress $meshEntry.ingress.enabled }}
{{- $role := "ingress" }}
{{- $cfg := $meshEntry.ingress }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuma.mesh.zoneproxy.serviceName" (dict "root" $ "meshName" $meshName "role" $role "nameOverride" (and $cfg.service $cfg.service.name)) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kuma.mesh.zoneproxy.labels" (dict "root" $ "meshName" $meshName "role" $role) | nindent 4 }}
    k8s.kuma.io/zone-proxy-type: {{ $role }}
  {{- if and $cfg.service $cfg.service.annotations }}
  annotations:
    {{- range $key, $value := $cfg.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ default "LoadBalancer" (and $cfg.service $cfg.service.type) }}
  ports:
    - port: {{ default 10001 (and $cfg.service $cfg.service.port) }}
      protocol: TCP
      targetPort: 10001
  selector:
    {{- include "kuma.mesh.zoneproxy.selectorLabels" (dict "root" $ "meshName" $meshName "role" $role) | nindent 4 }}
{{- end }}

{{- if and $meshEntry.egress $meshEntry.egress.enabled }}
{{- $role := "egress" }}
{{- $cfg := $meshEntry.egress }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuma.mesh.zoneproxy.serviceName" (dict "root" $ "meshName" $meshName "role" $role "nameOverride" (and $cfg.service $cfg.service.name)) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kuma.mesh.zoneproxy.labels" (dict "root" $ "meshName" $meshName "role" $role) | nindent 4 }}
    k8s.kuma.io/zone-proxy-type: {{ $role }}
  {{- if and $cfg.service $cfg.service.annotations }}
  annotations:
    {{- range $key, $value := $cfg.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ default "ClusterIP" (and $cfg.service $cfg.service.type) }}
  ports:
    - port: {{ default 10002 (and $cfg.service $cfg.service.port) }}
      protocol: TCP
      targetPort: 10002
  selector:
    {{- include "kuma.mesh.zoneproxy.selectorLabels" (dict "root" $ "meshName" $meshName "role" $role) | nindent 4 }}
{{- end }}

{{- end }}
