{{- $federated := $.Values.controlPlane.kdsGlobalAddress }}
{{- range $meshEntry := .Values.meshes }}
{{- $meshName := $meshEntry.name }}

{{- if and $meshEntry.createMesh (not $federated) }}
---
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: {{ $meshName }}
{{- end }}

{{- if and $meshEntry.createPolicies (not $federated) }}
{{- $ns := $.Release.Namespace }}

{{- range $policy := $meshEntry.createPolicies }}

{{- if eq $policy "MeshTimeout" }}
---
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: {{ printf "mesh-timeout-all-%s.%s" $meshName $ns }}
  namespace: {{ $ns }}
  labels:
    kuma.io/mesh: {{ $meshName }}
spec:
  targetRef:
    kind: Mesh
    proxyTypes:
      - Sidecar
  from:
    - targetRef:
        kind: Mesh
      default:
        connectionTimeout: 10s
        idleTimeout: 2h
        http:
          requestTimeout: 0s
          streamIdleTimeout: 1h
          maxStreamDuration: 0s
  to:
    - targetRef:
        kind: Mesh
      default:
        connectionTimeout: 5s
        idleTimeout: 1h
        http:
          requestTimeout: 15s
          streamIdleTimeout: 30m
---
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: {{ printf "mesh-gateways-timeout-all-%s.%s" $meshName $ns }}
  namespace: {{ $ns }}
  labels:
    kuma.io/mesh: {{ $meshName }}
spec:
  targetRef:
    kind: Mesh
    proxyTypes:
      - Gateway
  from:
    - targetRef:
        kind: Mesh
      default:
        idleTimeout: 5m
        http:
          streamIdleTimeout: 5s
          requestHeadersTimeout: 500ms
  to:
    - targetRef:
        kind: Mesh
      default:
        idleTimeout: 1h
        http:
          streamIdleTimeout: 5s
{{- end }}

{{- if eq $policy "MeshCircuitBreaker" }}
---
apiVersion: kuma.io/v1alpha1
kind: MeshCircuitBreaker
metadata:
  name: {{ printf "mesh-circuit-breaker-all-%s.%s" $meshName $ns }}
  namespace: {{ $ns }}
  labels:
    kuma.io/mesh: {{ $meshName }}
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        connectionLimits:
          maxConnections: 1024
          maxPendingRequests: 1024
          maxRequests: 1024
          maxRetries: 3
{{- end }}

{{- if eq $policy "MeshRetry" }}
---
apiVersion: kuma.io/v1alpha1
kind: MeshRetry
metadata:
  name: {{ printf "mesh-retry-all-%s.%s" $meshName $ns }}
  namespace: {{ $ns }}
  labels:
    kuma.io/mesh: {{ $meshName }}
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        tcp:
          maxConnectAttempt: 5
        http:
          numRetries: 5
          perTryTimeout: 16s
          backOff:
            baseInterval: 25ms
            maxInterval: 250ms
        grpc:
          numRetries: 5
          perTryTimeout: 16s
          backOff:
            baseInterval: 25ms
            maxInterval: 250ms
{{- end }}

{{- end }}
{{- end }}

{{- end }}
