// Generated by tools/policy-gen. DO NOT EDIT.
// Run "make generate" to update this file.

package v1alpha1

import (
	_ "embed"
	"errors"
	"fmt"

	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apiextensions-apiserver/pkg/apiserver/schema"
	"k8s.io/kube-openapi/pkg/validation/strfmt"
	"k8s.io/kube-openapi/pkg/validation/validate"
	"sigs.k8s.io/yaml"

	"github.com/kumahq/kuma/v2/pkg/core/resources/model"
)

//go:embed rest.yaml
var rawOpenAPISpec []byte

func init() {
	var structuralSchema *schema.Structural
	var v1JsonSchemaProps *apiextensionsv1.JSONSchemaProps
	var validator *validate.SchemaValidator
	if rawOpenAPISpec != nil {
		// Parse OpenAPI spec to extract the schema

		var openapiSpec map[string]interface{}
		if err := yaml.Unmarshal(rawOpenAPISpec, &openapiSpec); err != nil {
			panic(err)
		}

		// Extract schema from .components.schemas.MeshCircuitBreakerItem
		components, ok := openapiSpec["components"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("components not found in OpenAPI spec"))
		}
		schemas, ok := components["schemas"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("schemas not found in components"))
		}
		schemaItem, ok := schemas["MeshCircuitBreakerItem"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("MeshCircuitBreakerItem schema not found"))
		}

		// Marshal the extracted schema back to YAML to unmarshal into JSONSchemaProps
		schemaBytes, err := yaml.Marshal(schemaItem)
		if err != nil {
			panic(err)
		}

		if err := yaml.Unmarshal(schemaBytes, &v1JsonSchemaProps); err != nil {
			panic(err)
		}
		var jsonSchemaProps apiextensions.JSONSchemaProps
		err = apiextensionsv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(v1JsonSchemaProps, &jsonSchemaProps, nil)
		if err != nil {
			panic(err)
		}
		structuralSchema, err = schema.NewStructural(&jsonSchemaProps)
		if err != nil {
			panic(err)
		}
		schemaObject := structuralSchema.ToKubeOpenAPI()
		validator = validate.NewSchemaValidator(schemaObject, nil, "", strfmt.Default)
	}
	rawOpenAPISpec = nil
	MeshCircuitBreakerResourceTypeDescriptor.Validator = validator
	MeshCircuitBreakerResourceTypeDescriptor.StructuralSchema = structuralSchema
}

const (
	MeshCircuitBreakerType model.ResourceType = "MeshCircuitBreaker"
)

var _ model.Resource = &MeshCircuitBreakerResource{}

type MeshCircuitBreakerResource struct {
	Meta model.ResourceMeta
	Spec *MeshCircuitBreaker
}

func NewMeshCircuitBreakerResource() *MeshCircuitBreakerResource {
	return &MeshCircuitBreakerResource{
		Spec: &MeshCircuitBreaker{},
	}
}

func (t *MeshCircuitBreakerResource) GetMeta() model.ResourceMeta {
	return t.Meta
}

func (t *MeshCircuitBreakerResource) SetMeta(m model.ResourceMeta) {
	t.Meta = m
}

func (t *MeshCircuitBreakerResource) GetSpec() model.ResourceSpec {
	return t.Spec
}

func (t *MeshCircuitBreakerResource) SetSpec(spec model.ResourceSpec) error {
	protoType, ok := spec.(*MeshCircuitBreaker)
	if !ok {
		return fmt.Errorf("invalid type %T for Spec", spec)
	} else {
		if protoType == nil {
			t.Spec = &MeshCircuitBreaker{}
		} else {
			t.Spec = protoType
		}
		return nil
	}
}

func (t *MeshCircuitBreakerResource) GetStatus() model.ResourceStatus {
	return nil
}

func (t *MeshCircuitBreakerResource) SetStatus(model.ResourceStatus) error {
	return errors.New("status not supported")
}

func (t *MeshCircuitBreakerResource) Descriptor() model.ResourceTypeDescriptor {
	return MeshCircuitBreakerResourceTypeDescriptor
}

func (t *MeshCircuitBreakerResource) Validate() error {
	if v, ok := interface{}(t).(interface{ validate() error }); !ok {
		return nil
	} else {
		return v.validate()
	}
}

var _ model.ResourceList = &MeshCircuitBreakerResourceList{}

type MeshCircuitBreakerResourceList struct {
	Items      []*MeshCircuitBreakerResource
	Pagination model.Pagination
}

func (l *MeshCircuitBreakerResourceList) GetItems() []model.Resource {
	res := make([]model.Resource, len(l.Items))
	for i, elem := range l.Items {
		res[i] = elem
	}
	return res
}

func (l *MeshCircuitBreakerResourceList) GetItemType() model.ResourceType {
	return MeshCircuitBreakerType
}

func (l *MeshCircuitBreakerResourceList) NewItem() model.Resource {
	return NewMeshCircuitBreakerResource()
}

func (l *MeshCircuitBreakerResourceList) AddItem(r model.Resource) error {
	if trr, ok := r.(*MeshCircuitBreakerResource); ok {
		l.Items = append(l.Items, trr)
		return nil
	} else {
		return model.ErrorInvalidItemType((*MeshCircuitBreakerResource)(nil), r)
	}
}

func (l *MeshCircuitBreakerResourceList) GetPagination() *model.Pagination {
	return &l.Pagination
}

func (l *MeshCircuitBreakerResourceList) SetPagination(p model.Pagination) {
	l.Pagination = p
}

var MeshCircuitBreakerResourceTypeDescriptor = model.ResourceTypeDescriptor{
	Name:                         MeshCircuitBreakerType,
	Resource:                     NewMeshCircuitBreakerResource(),
	ResourceList:                 &MeshCircuitBreakerResourceList{},
	Scope:                        model.ScopeMesh,
	KDSFlags:                     model.GlobalToZonesFlag | model.ZoneToGlobalFlag | model.SyncedAcrossZonesFlag,
	WsPath:                       "meshcircuitbreakers",
	KumactlArg:                   "meshcircuitbreaker",
	KumactlListArg:               "meshcircuitbreakers",
	AllowToInspect:               true,
	IsPolicy:                     true,
	IsDestination:                false,
	IsExperimental:               false,
	SingularDisplayName:          "Mesh Circuit Breaker",
	PluralDisplayName:            "Mesh Circuit Breakers",
	IsPluginOriginated:           true,
	IsTargetRefBased:             true,
	HasToTargetRef:               true,
	HasFromTargetRef:             true,
	HasRulesTargetRef:            true,
	HasStatus:                    false,
	AllowedOnSystemNamespaceOnly: false,
	ShortName:                    "mcb",
	IsFromAsRules:                true,
}
