package framework

import (
	"context"
	"fmt"

	"github.com/gruntwork-io/terratest/modules/retry"
	"github.com/pkg/errors"

	mesh_proto "github.com/kumahq/kuma/v3/api/mesh/v1alpha1"
	meshidentity_api "github.com/kumahq/kuma/v3/pkg/core/resources/apis/meshidentity/api/v1alpha1"
	meshservice_api "github.com/kumahq/kuma/v3/pkg/core/resources/apis/meshservice/api/v1alpha1"
	meshtrust_api "github.com/kumahq/kuma/v3/pkg/core/resources/apis/meshtrust/api/v1alpha1"
	core_model "github.com/kumahq/kuma/v3/pkg/core/resources/model"
	"github.com/kumahq/kuma/v3/pkg/core/resources/model/rest"
	"github.com/kumahq/kuma/v3/pkg/kds/hash"
	"github.com/kumahq/kuma/v3/pkg/test/resources/builders"
	"github.com/kumahq/kuma/v3/pkg/util/pointer"
)

// MeshIdentityBundled installs a MeshIdentity backed by a self-signed,
// autogenerated CA. Install it on Global so KDS distributes it to every zone;
// each zone then generates its own CA and, with meshTrustCreation enabled, a
// local MeshTrust holding that CA.
//
// Zones do not learn about each other's CAs on their own - use
// DistributeMeshTrusts for that.
func MeshIdentityBundled(mesh string, name string) InstallFunc {
	return YamlUniversal(fmt.Sprintf(`
type: MeshIdentity
name: %s
mesh: %s
spec:
  selector:
    dataplane:
      matchLabels: {}
  spiffeID:
    trustDomain: "{{ .Mesh }}.{{ .Zone }}.mesh.local"
  provider:
    type: Bundled
    bundled:
      meshTrustCreation: Enabled
      insecureAllowSelfSigned: true
      certificateParameters:
        expiry: 24h
      autogenerate:
        enabled: true
`, name, mesh))
}

// MeshIdentitySpiffeIDOnly installs a MeshIdentity with no provider. The control
// plane reports such an identity as PartiallyReady - "SpiffeID providing only
// mode" - so it hands no certificate to any proxy, yet every MeshService its
// selector matches already publishes the SPIFFE ID under spec.identities.
//
// Install it before MeshIdentityBundled of the same name whenever a suite must
// not drop a request while mTLS is switched on: a proxy starts requiring mTLS
// the moment it receives its certificate, but the SAN it validates the peer
// against comes from the MeshService status, which a separate reconciler
// publishes on its own interval. Going straight to Bundled leaves a window in
// which the client already speaks mTLS while still expecting the legacy
// spiffe://{mesh}/{service} SAN, and every request in it fails SAN
// verification.
func MeshIdentitySpiffeIDOnly(mesh string, name string) InstallFunc {
	return YamlUniversal(fmt.Sprintf(`
type: MeshIdentity
name: %s
mesh: %s
spec:
  selector:
    dataplane:
      matchLabels: {}
  spiffeID:
    trustDomain: "{{ .Mesh }}.{{ .Zone }}.mesh.local"
`, name, mesh))
}

// WaitForMeshServiceSpiffeIDs blocks until each named MeshService publishes at
// least one SpiffeID identity. Pair it with MeshIdentitySpiffeIDOnly: once this
// returns, the clients of those services validate the peer against the SPIFFE
// ID the MeshIdentity will issue, so handing out certificates no longer breaks
// in-flight requests.
func WaitForMeshServiceSpiffeIDs(cluster Cluster, mesh string, services ...string) error {
	for _, service := range services {
		_, err := retry.DoWithRetryContextE(
			cluster.GetTesting(), context.Background(),
			"wait for SpiffeID identity on MeshService "+service,
			DefaultRetries, DefaultTimeout,
			func() (string, error) {
				out, err := cluster.GetKumactlOptions().
					RunKumactlAndGetOutput("get", "meshservice", service, "-m", mesh, "-ojson")
				if err != nil {
					return "", err
				}
				res, err := rest.JSON.Unmarshal([]byte(out), meshservice_api.MeshServiceResourceTypeDescriptor)
				if err != nil {
					return "", err
				}
				for _, identity := range pointer.Deref(res.GetSpec().(*meshservice_api.MeshService).Identities) {
					if identity.Type == meshservice_api.MeshServiceIdentitySpiffeIDType {
						return "", nil
					}
				}
				return "", errors.Errorf("MeshService %s has no SpiffeID identity yet", service)
			})
		if err != nil {
			return err
		}
	}
	return nil
}

// MeshIdentityBundledKubernetes is the Kubernetes counterpart of
// MeshIdentityBundled. It lives in the CP namespace and carries the zone origin
// label, so a zone CP picks it up even when it later federates to a Global.
func MeshIdentityBundledKubernetes(mesh string, name string) InstallFunc {
	return YamlK8s(fmt.Sprintf(`
apiVersion: kuma.io/v1alpha1
kind: MeshIdentity
metadata:
  name: %s
  namespace: %s
  labels:
    kuma.io/mesh: %s
    kuma.io/origin: zone
spec:
  selector:
    dataplane:
      matchLabels: {}
  spiffeID:
    trustDomain: "{{ .Mesh }}.{{ .Zone }}.mesh.local"
    path: "/ns/{{ .Namespace }}/sa/{{ .ServiceAccount }}"
  provider:
    type: Bundled
    bundled:
      meshTrustCreation: Enabled
      insecureAllowSelfSigned: true
      certificateParameters:
        expiry: 24h
      autogenerate:
        enabled: true
`, name, Config.KumaNamespace, mesh))
}

// MeshIdentityTrustDomain returns the trust domain MeshIdentityBundled renders
// in the given zone. Use it to build MeshTrafficPermission rules.
func MeshIdentityTrustDomain(mesh string, zone Cluster) string {
	return fmt.Sprintf("%s.%s.mesh.local", mesh, zone.ZoneName())
}

// MeshIdentityTrustDomains returns the trust domains of every given zone, in
// the order they were passed. Feed it straight into
// MeshTrafficPermissionAllowAll*WorkloadIdentity to allow all of them.
func MeshIdentityTrustDomains(mesh string, zones ...Cluster) []string {
	trustDomains := make([]string, 0, len(zones))
	for _, zone := range zones {
		trustDomains = append(trustDomains, MeshIdentityTrustDomain(mesh, zone))
	}
	return trustDomains
}

// DistributeMeshTrusts copies the MeshTrust each zone generated from the named
// MeshIdentity into every other zone, so proxies accept peer certificates
// issued by a different zone's CA.
//
// A Bundled MeshIdentity mints a separate CA per zone. MeshTrust is a
// zone-origin resource, so KDS carries it up to Global but never back down to
// the other zones - without this step cross-zone mTLS fails on an unknown
// issuer.
func DistributeMeshTrusts(global Cluster, mesh string, identityName string, zones ...Cluster) error {
	// There is nothing to distribute below two zones, and returning nil would
	// report success for a setup step that did nothing - the suite would then
	// fail much later on an unknown issuer.
	if len(zones) < 2 {
		return errors.Errorf("DistributeMeshTrusts needs at least two zones, got %d", len(zones))
	}

	trusts := map[string]*meshtrust_api.MeshTrust{}
	for _, zone := range zones {
		if err := waitForMeshIdentity(mesh, identityName, zone); err != nil {
			return err
		}
		trust, err := zoneMeshTrust(global, mesh, identityName, zone)
		if err != nil {
			return err
		}
		trusts[zone.ZoneName()] = trust
	}

	for _, target := range zones {
		for _, source := range zones {
			if source.ZoneName() == target.ZoneName() {
				continue
			}
			if err := installMeshTrust(target, mesh, source.ZoneName(), trusts[source.ZoneName()]); err != nil {
				return err
			}
		}
	}
	return nil
}

// waitForMeshIdentity waits until KDS has delivered the MeshIdentity to the
// zone. The zone cannot generate its CA (and therefore its MeshTrust) before
// that happens.
func waitForMeshIdentity(mesh string, identityName string, zone Cluster) error {
	name := hash.HashedName(mesh, identityName)
	if _, ok := zone.(*K8sCluster); ok {
		name = fmt.Sprintf("%s.%s", name, Config.KumaNamespace)
	}
	return WaitForResource(
		meshidentity_api.MeshIdentityResourceTypeDescriptor,
		core_model.ResourceKey{Mesh: mesh, Name: name},
		zone,
	)
}

// zoneMeshTrust reads the zone's MeshTrust from Global. The zone names it after
// its local copy of the MeshIdentity, and KDS hashes that name again with the
// zone (and the namespace on Kubernetes) when syncing it up.
func zoneMeshTrust(global Cluster, mesh string, identityName string, zone Cluster) (*meshtrust_api.MeshTrust, error) {
	values := []string{zone.ZoneName()}
	if _, ok := zone.(*K8sCluster); ok {
		values = append(values, Config.KumaNamespace)
	}
	name := hash.HashedName(mesh, hash.HashedName(mesh, identityName), values...)

	var trust *meshtrust_api.MeshTrust
	_, err := retry.DoWithRetryContextE(
		global.GetTesting(), context.Background(),
		"get MeshTrust "+name,
		DefaultRetries, DefaultTimeout,
		func() (string, error) {
			out, err := global.GetKumactlOptions().RunKumactlAndGetOutput("get", "meshtrust", "-m", mesh, name, "-ojson")
			if err != nil {
				return "", err
			}
			res, err := rest.JSON.Unmarshal([]byte(out), meshtrust_api.MeshTrustResourceTypeDescriptor)
			if err != nil {
				return "", err
			}
			spec := res.GetSpec().(*meshtrust_api.MeshTrust)
			// installMeshTrust copies the PEM of the first bundle, so a bundle
			// in any other format would leave it nil.
			if len(spec.CABundles) == 0 || spec.CABundles[0].PEM == nil {
				return "", errors.Errorf("MeshTrust %s has no PEM CA bundle yet", name)
			}
			trust = spec
			return "", nil
		})
	return trust, err
}

func installMeshTrust(target Cluster, mesh string, sourceZone string, trust *meshtrust_api.MeshTrust) error {
	// The name carries the mesh: on Kubernetes every mesh puts its MeshTrusts
	// in the same namespace, so a mesh-agnostic name makes suites running in
	// parallel overwrite each other's trust and break cross-zone mTLS.
	builder := builders.MeshTrust().
		WithName(fmt.Sprintf("%s-trust-of-zone-%s", mesh, sourceZone)).
		WithMesh(mesh).
		WithLabels(map[string]string{
			mesh_proto.ResourceOriginLabel: string(mesh_proto.ZoneResourceOrigin),
			mesh_proto.ZoneTag:             target.ZoneName(),
		}).
		WithCA(trust.CABundles[0].PEM.Value).
		WithTrustDomain(trust.TrustDomain)

	if _, ok := target.(*K8sCluster); ok {
		return NewClusterSetup().
			Install(YamlK8s(builder.WithNamespace(Config.KumaNamespace).KubeYaml())).
			Setup(target)
	}
	return NewClusterSetup().
		Install(YamlUniversal(builder.UniYaml())).
		Setup(target)
}
