// Generated by tools/policy-gen. DO NOT EDIT.
// Run "make generate" to update this file.

package v1alpha1

import (
	_ "embed"
	"errors"
	"fmt"

	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apiextensions-apiserver/pkg/apiserver/schema"
	"k8s.io/kube-openapi/pkg/validation/strfmt"
	"k8s.io/kube-openapi/pkg/validation/validate"
	"sigs.k8s.io/yaml"

	"github.com/kumahq/kuma/pkg/core/resources/model"
)

//go:embed schema.yaml
var rawSchema []byte

func init() {
	var structuralSchema *schema.Structural
	var v1JsonSchemaProps *apiextensionsv1.JSONSchemaProps
	var validator *validate.SchemaValidator
	if rawSchema != nil {
		if err := yaml.Unmarshal(rawSchema, &v1JsonSchemaProps); err != nil {
			panic(err)
		}
		var jsonSchemaProps apiextensions.JSONSchemaProps
		err := apiextensionsv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(v1JsonSchemaProps, &jsonSchemaProps, nil)
		if err != nil {
			panic(err)
		}
		structuralSchema, err = schema.NewStructural(&jsonSchemaProps)
		if err != nil {
			panic(err)
		}
		schemaObject := structuralSchema.ToKubeOpenAPI()
		validator = validate.NewSchemaValidator(schemaObject, nil, "", strfmt.Default)
	}
	rawSchema = nil
	MeshTrustResourceTypeDescriptor.Validator = validator
	MeshTrustResourceTypeDescriptor.StructuralSchema = structuralSchema
}

const (
	MeshTrustType model.ResourceType = "MeshTrust"
)

var _ model.Resource = &MeshTrustResource{}

type MeshTrustResource struct {
	Meta model.ResourceMeta
	Spec *MeshTrust
}

func NewMeshTrustResource() *MeshTrustResource {
	return &MeshTrustResource{
		Spec: &MeshTrust{},
	}
}

func (t *MeshTrustResource) GetMeta() model.ResourceMeta {
	return t.Meta
}

func (t *MeshTrustResource) SetMeta(m model.ResourceMeta) {
	t.Meta = m
}

func (t *MeshTrustResource) GetSpec() model.ResourceSpec {
	return t.Spec
}

func (t *MeshTrustResource) SetSpec(spec model.ResourceSpec) error {
	protoType, ok := spec.(*MeshTrust)
	if !ok {
		return fmt.Errorf("invalid type %T for Spec", spec)
	} else {
		if protoType == nil {
			t.Spec = &MeshTrust{}
		} else {
			t.Spec = protoType
		}
		return nil
	}
}

func (t *MeshTrustResource) GetStatus() model.ResourceStatus {
	return nil
}

func (t *MeshTrustResource) SetStatus(model.ResourceStatus) error {
	return errors.New("status not supported")
}

func (t *MeshTrustResource) Descriptor() model.ResourceTypeDescriptor {
	return MeshTrustResourceTypeDescriptor
}

func (t *MeshTrustResource) Validate() error {
	if v, ok := interface{}(t).(interface{ validate() error }); !ok {
		return nil
	} else {
		return v.validate()
	}
}

var _ model.ResourceList = &MeshTrustResourceList{}

type MeshTrustResourceList struct {
	Items      []*MeshTrustResource
	Pagination model.Pagination
}

func (l *MeshTrustResourceList) GetItems() []model.Resource {
	res := make([]model.Resource, len(l.Items))
	for i, elem := range l.Items {
		res[i] = elem
	}
	return res
}

func (l *MeshTrustResourceList) GetItemType() model.ResourceType {
	return MeshTrustType
}

func (l *MeshTrustResourceList) NewItem() model.Resource {
	return NewMeshTrustResource()
}

func (l *MeshTrustResourceList) AddItem(r model.Resource) error {
	if trr, ok := r.(*MeshTrustResource); ok {
		l.Items = append(l.Items, trr)
		return nil
	} else {
		return model.ErrorInvalidItemType((*MeshTrustResource)(nil), r)
	}
}

func (l *MeshTrustResourceList) GetPagination() *model.Pagination {
	return &l.Pagination
}

func (l *MeshTrustResourceList) SetPagination(p model.Pagination) {
	l.Pagination = p
}

var MeshTrustResourceTypeDescriptor = model.ResourceTypeDescriptor{
	Name:                         MeshTrustType,
	Resource:                     NewMeshTrustResource(),
	ResourceList:                 &MeshTrustResourceList{},
	Scope:                        model.ScopeMesh,
	KDSFlags:                     model.GlobalToZonesFlag | model.ZoneToGlobalFlag,
	WsPath:                       "meshtrusts",
	KumactlArg:                   "meshtrust",
	KumactlListArg:               "meshtrusts",
	AllowToInspect:               false,
	IsPolicy:                     false,
	IsDestination:                false,
	IsExperimental:               false,
	SingularDisplayName:          "Mesh Trust",
	PluralDisplayName:            "Mesh Trusts",
	IsPluginOriginated:           true,
	IsTargetRefBased:             false,
	HasToTargetRef:               false,
	HasFromTargetRef:             false,
	HasRulesTargetRef:            false,
	HasStatus:                    false,
	AllowedOnSystemNamespaceOnly: true,
	IsReferenceableInTo:          false,
	ShortName:                    "mtrust",
	IsFromAsRules:                false,
}
