package consts

import (
	"regexp"
)

const (
	Iptables  = "iptables"
	Ip6tables = "ip6tables"
)

// IptablesCommandByFamily maps a boolean value indicating IPv4 (false) or IPv6
// (true) usage to the corresponding iptables command name. This allows for code
// to be written generically without duplicating logic for both IPv4 and IPv6.
var IptablesCommandByFamily = map[bool]string{
	false: Iptables,
	true:  Ip6tables,
}

// IPTypeMap is a map that translates a boolean value to a string representing
// the type of IP address (IPv4 or IPv6). The key is a boolean where 'false'
// corresponds to "IPv4" and 'true' corresponds to "IPv6".
var IPTypeMap = map[bool]string{
	false: "IPv4",
	true:  "IPv6",
}

// Default ports used for iptables redirection.
const (
	DefaultRedirectInbountPort     uint16 = 15006
	DefaultRedirectInbountPortIPv6 uint16 = 15010
	DefaultRedirectOutboundPort    uint16 = 15001
	DefaultRedirectDNSPort         uint16 = 15053
)

const (
	DNSPort           uint16 = 53
	LocalhostIPv4            = "127.0.0.1"
	LocalhostCIDRIPv4        = "127.0.0.1/32"
	LocalhostIPv6            = "[::1]"
	LocalhostCIDRIPv6        = "::1/128"
	// InboundPassthroughSourceAddressCIDRIPv4
	// TODO (bartsmykla): add some description
	InboundPassthroughSourceAddressCIDRIPv4 = "127.0.0.6/32"
	InboundPassthroughSourceAddressCIDRIPv6 = "::6/128"
	OutputLogPrefix                         = "OUTPUT:"
	PreroutingLogPrefix                     = "PREROUTING:"
	UDP                                     = "udp"
	TCP                                     = "tcp"
)

type TableName string

const (
	TableNat    TableName = "nat"
	TableRaw    TableName = "raw"
	TableMangle TableName = "mangle"
)

const (
	ChainPrerouting   = "PREROUTING"
	ChainInput        = "INPUT"
	ChainForward      = "FORWARD"
	ChainOutput       = "OUTPUT"
	ChainPostrouting  = "POSTROUTING"
	ChainDockerOutput = "DOCKER_OUTPUT"
)

// DockerOutputChainRegex is a regular expression used to identify the presence
// of a custom chain named "DOCKER_OUTPUT" in iptables rules.
var DockerOutputChainRegex = regexp.MustCompile(`(?m)^:DOCKER_OUTPUT`)

const (
	FlagTable   = "-t"
	FlagMatch   = "-m"
	FlagHelp    = "-h"
	FlagVersion = "--version" // there is no short version of this flag

	// commands
	FlagAppend   = "-A"
	FlagInsert   = "-I"
	FlagNewChain = "-N"

	// iptables-restore
	FlagWait         = "--wait"
	FlagWaitInterval = "--wait-interval"
	FlagNoFlush      = "--noflush"
)

// FlagVariationsMap maps a flag name (e.g., "-t") to a map containing its long
// (true) and short (false) flag representations. This allows for code to easily
// look up the appropriate flag based on desired usage (short or long).
var FlagVariationsMap = map[string]map[bool]string{
	FlagAppend: {
		true:  "--append",
		false: FlagAppend,
	},
	FlagInsert: {
		true:  "--insert",
		false: FlagInsert,
	},
	FlagNewChain: {
		true:  "--new-chain",
		false: FlagNewChain,
	},
}

const (
	ModuleOwner     = "owner"
	ModuleTcp       = "tcp"
	ModuleUdp       = "udp"
	ModuleComment   = "comment"
	ModuleConntrack = "conntrack"
)

type IptablesMode string

const (
	IptablesModeNft    IptablesMode = "nft"
	IptablesModeLegacy IptablesMode = "legacy"
)

// Regexp used to parse the result of `iptables --version` then used to map to
// with IptablesMode
var IptablesModeRegex = regexp.MustCompile(`(?m)^ip6?tables(?:.*?\((.*?)\))?`)

// Map IptablesMode to the mode taken from the result of `iptables --version`
var IptablesModeMap = map[IptablesMode][]string{
	IptablesModeLegacy: {
		"legacy", // i.e. iptables v1.8.5 (legacy)
		"",       // i.e. iptables v1.6.1
	},
	IptablesModeNft: {"nf_tables"}, // i.e. iptables v1.8.9 (nf_tables)
}

// FallbackExecutablesSearchLocations is a list of directories to search for
// the iptables executables if it cannot be found in the user's PATH environment
// variable. This allows for some flexibility in environments where iptables
// may be installed in non-standard locations.
var FallbackExecutablesSearchLocations = []string{
	"/usr/sbin",
	"/sbin",
	"/usr/bin",
	"/bin",
}

// Debug log level for iptables LOG jump target
// ref. https://git.netfilter.org/iptables/tree/extensions/libebt_log.c#n27
const LogLevelDebug uint16 = 7

// IptablesRuleCommentPrefix defines a consistent prefix used in iptables rule
// comments. This prefix helps identify and distinguish rules that were
// specifically generated by our transparent proxy.
const IptablesRuleCommentPrefix = "kuma/mesh/transparent/proxy"

// IptablesChainsPrefix is the prefix used for naming custom iptables chains
// created for the transparent proxy. This prefix helps to clearly identify
// and differentiate the chains managed by the Kuma mesh from other iptables
// chains. The chains named with this prefix are used to apply specific rules
// necessary for the operation of the transparent proxy.
const IptablesChainsPrefix = "KUMA_MESH"
