// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesh/v1alpha1/mesh.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Mesh defines configuration of a single mesh.
type Mesh struct {
	// mTLS settings.
	// +optional
	Mtls *Mesh_Mtls `protobuf:"bytes,1,opt,name=mtls,proto3" json:"mtls,omitempty"`
	// Tracing settings.
	// +optional
	Tracing *Tracing `protobuf:"bytes,2,opt,name=tracing,proto3" json:"tracing,omitempty"`
	// Logging settings.
	// +optional
	Logging              *Logging `protobuf:"bytes,3,opt,name=logging,proto3" json:"logging,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mesh) Reset()         { *m = Mesh{} }
func (m *Mesh) String() string { return proto.CompactTextString(m) }
func (*Mesh) ProtoMessage()    {}
func (*Mesh) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{0}
}

func (m *Mesh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mesh.Unmarshal(m, b)
}
func (m *Mesh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mesh.Marshal(b, m, deterministic)
}
func (m *Mesh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mesh.Merge(m, src)
}
func (m *Mesh) XXX_Size() int {
	return xxx_messageInfo_Mesh.Size(m)
}
func (m *Mesh) XXX_DiscardUnknown() {
	xxx_messageInfo_Mesh.DiscardUnknown(m)
}

var xxx_messageInfo_Mesh proto.InternalMessageInfo

func (m *Mesh) GetMtls() *Mesh_Mtls {
	if m != nil {
		return m.Mtls
	}
	return nil
}

func (m *Mesh) GetTracing() *Tracing {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *Mesh) GetLogging() *Logging {
	if m != nil {
		return m.Logging
	}
	return nil
}

// mTLS settings of a Mesh.
type Mesh_Mtls struct {
	// Certificate Authority of a Mesh.
	// +optional
	Ca *CertificateAuthority `protobuf:"bytes,1,opt,name=ca,proto3" json:"ca,omitempty"`
	// If true, then mTLS will be enabled for given mesh
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mesh_Mtls) Reset()         { *m = Mesh_Mtls{} }
func (m *Mesh_Mtls) String() string { return proto.CompactTextString(m) }
func (*Mesh_Mtls) ProtoMessage()    {}
func (*Mesh_Mtls) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{0, 0}
}

func (m *Mesh_Mtls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mesh_Mtls.Unmarshal(m, b)
}
func (m *Mesh_Mtls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mesh_Mtls.Marshal(b, m, deterministic)
}
func (m *Mesh_Mtls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mesh_Mtls.Merge(m, src)
}
func (m *Mesh_Mtls) XXX_Size() int {
	return xxx_messageInfo_Mesh_Mtls.Size(m)
}
func (m *Mesh_Mtls) XXX_DiscardUnknown() {
	xxx_messageInfo_Mesh_Mtls.DiscardUnknown(m)
}

var xxx_messageInfo_Mesh_Mtls proto.InternalMessageInfo

func (m *Mesh_Mtls) GetCa() *CertificateAuthority {
	if m != nil {
		return m.Ca
	}
	return nil
}

func (m *Mesh_Mtls) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// CertificateAuthority defines configuration of a CA.
type CertificateAuthority struct {
	// Types that are valid to be assigned to Type:
	//	*CertificateAuthority_Builtin_
	Type                 isCertificateAuthority_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CertificateAuthority) Reset()         { *m = CertificateAuthority{} }
func (m *CertificateAuthority) String() string { return proto.CompactTextString(m) }
func (*CertificateAuthority) ProtoMessage()    {}
func (*CertificateAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{1}
}

func (m *CertificateAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateAuthority.Unmarshal(m, b)
}
func (m *CertificateAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateAuthority.Marshal(b, m, deterministic)
}
func (m *CertificateAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateAuthority.Merge(m, src)
}
func (m *CertificateAuthority) XXX_Size() int {
	return xxx_messageInfo_CertificateAuthority.Size(m)
}
func (m *CertificateAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateAuthority proto.InternalMessageInfo

type isCertificateAuthority_Type interface {
	isCertificateAuthority_Type()
}

type CertificateAuthority_Builtin_ struct {
	Builtin *CertificateAuthority_Builtin `protobuf:"bytes,1,opt,name=builtin,proto3,oneof"`
}

func (*CertificateAuthority_Builtin_) isCertificateAuthority_Type() {}

func (m *CertificateAuthority) GetType() isCertificateAuthority_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *CertificateAuthority) GetBuiltin() *CertificateAuthority_Builtin {
	if x, ok := m.GetType().(*CertificateAuthority_Builtin_); ok {
		return x.Builtin
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CertificateAuthority) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CertificateAuthority_Builtin_)(nil),
	}
}

// Builtin defines configuration of the builtin CA.
type CertificateAuthority_Builtin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateAuthority_Builtin) Reset()         { *m = CertificateAuthority_Builtin{} }
func (m *CertificateAuthority_Builtin) String() string { return proto.CompactTextString(m) }
func (*CertificateAuthority_Builtin) ProtoMessage()    {}
func (*CertificateAuthority_Builtin) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{1, 0}
}

func (m *CertificateAuthority_Builtin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateAuthority_Builtin.Unmarshal(m, b)
}
func (m *CertificateAuthority_Builtin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateAuthority_Builtin.Marshal(b, m, deterministic)
}
func (m *CertificateAuthority_Builtin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateAuthority_Builtin.Merge(m, src)
}
func (m *CertificateAuthority_Builtin) XXX_Size() int {
	return xxx_messageInfo_CertificateAuthority_Builtin.Size(m)
}
func (m *CertificateAuthority_Builtin) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateAuthority_Builtin.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateAuthority_Builtin proto.InternalMessageInfo

// Tracing defines tracing configuration of the mesh.
type Tracing struct {
	// Types that are valid to be assigned to Type:
	//	*Tracing_Zipkin_
	Type                 isTracing_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Tracing) Reset()         { *m = Tracing{} }
func (m *Tracing) String() string { return proto.CompactTextString(m) }
func (*Tracing) ProtoMessage()    {}
func (*Tracing) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{2}
}

func (m *Tracing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing.Unmarshal(m, b)
}
func (m *Tracing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing.Marshal(b, m, deterministic)
}
func (m *Tracing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing.Merge(m, src)
}
func (m *Tracing) XXX_Size() int {
	return xxx_messageInfo_Tracing.Size(m)
}
func (m *Tracing) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing proto.InternalMessageInfo

type isTracing_Type interface {
	isTracing_Type()
}

type Tracing_Zipkin_ struct {
	Zipkin *Tracing_Zipkin `protobuf:"bytes,1,opt,name=zipkin,proto3,oneof"`
}

func (*Tracing_Zipkin_) isTracing_Type() {}

func (m *Tracing) GetType() isTracing_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Tracing) GetZipkin() *Tracing_Zipkin {
	if x, ok := m.GetType().(*Tracing_Zipkin_); ok {
		return x.Zipkin
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tracing) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tracing_Zipkin_)(nil),
	}
}

// Zipkin defined configuration of Zipkin tracer.
type Tracing_Zipkin struct {
	// Address of Zipkin collector.
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_Zipkin) Reset()         { *m = Tracing_Zipkin{} }
func (m *Tracing_Zipkin) String() string { return proto.CompactTextString(m) }
func (*Tracing_Zipkin) ProtoMessage()    {}
func (*Tracing_Zipkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{2, 0}
}

func (m *Tracing_Zipkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Zipkin.Unmarshal(m, b)
}
func (m *Tracing_Zipkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Zipkin.Marshal(b, m, deterministic)
}
func (m *Tracing_Zipkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Zipkin.Merge(m, src)
}
func (m *Tracing_Zipkin) XXX_Size() int {
	return xxx_messageInfo_Tracing_Zipkin.Size(m)
}
func (m *Tracing_Zipkin) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Zipkin.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Zipkin proto.InternalMessageInfo

func (m *Tracing_Zipkin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Logging struct {
	// Name of the default backend
	DefaultBackend string `protobuf:"bytes,1,opt,name=defaultBackend,proto3" json:"defaultBackend,omitempty"`
	// List of available logging backends
	Backends             []*LoggingBackend `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Logging) Reset()         { *m = Logging{} }
func (m *Logging) String() string { return proto.CompactTextString(m) }
func (*Logging) ProtoMessage()    {}
func (*Logging) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{3}
}

func (m *Logging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logging.Unmarshal(m, b)
}
func (m *Logging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logging.Marshal(b, m, deterministic)
}
func (m *Logging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logging.Merge(m, src)
}
func (m *Logging) XXX_Size() int {
	return xxx_messageInfo_Logging.Size(m)
}
func (m *Logging) XXX_DiscardUnknown() {
	xxx_messageInfo_Logging.DiscardUnknown(m)
}

var xxx_messageInfo_Logging proto.InternalMessageInfo

func (m *Logging) GetDefaultBackend() string {
	if m != nil {
		return m.DefaultBackend
	}
	return ""
}

func (m *Logging) GetBackends() []*LoggingBackend {
	if m != nil {
		return m.Backends
	}
	return nil
}

// LoggingBackend defines logging backend available to mesh. Backends can be
// used in TrafficLog rules.
type LoggingBackend struct {
	// Name of the backend, can be then used in Mesh.logging.defaultBackend or in
	// TrafficLogging
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Format of access logs. Placehodlers available on
	// https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*LoggingBackend_File_
	//	*LoggingBackend_Tcp_
	Type                 isLoggingBackend_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoggingBackend) Reset()         { *m = LoggingBackend{} }
func (m *LoggingBackend) String() string { return proto.CompactTextString(m) }
func (*LoggingBackend) ProtoMessage()    {}
func (*LoggingBackend) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{4}
}

func (m *LoggingBackend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggingBackend.Unmarshal(m, b)
}
func (m *LoggingBackend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggingBackend.Marshal(b, m, deterministic)
}
func (m *LoggingBackend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggingBackend.Merge(m, src)
}
func (m *LoggingBackend) XXX_Size() int {
	return xxx_messageInfo_LoggingBackend.Size(m)
}
func (m *LoggingBackend) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggingBackend.DiscardUnknown(m)
}

var xxx_messageInfo_LoggingBackend proto.InternalMessageInfo

func (m *LoggingBackend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoggingBackend) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type isLoggingBackend_Type interface {
	isLoggingBackend_Type()
}

type LoggingBackend_File_ struct {
	File *LoggingBackend_File `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

type LoggingBackend_Tcp_ struct {
	Tcp *LoggingBackend_Tcp `protobuf:"bytes,4,opt,name=tcp,proto3,oneof"`
}

func (*LoggingBackend_File_) isLoggingBackend_Type() {}

func (*LoggingBackend_Tcp_) isLoggingBackend_Type() {}

func (m *LoggingBackend) GetType() isLoggingBackend_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *LoggingBackend) GetFile() *LoggingBackend_File {
	if x, ok := m.GetType().(*LoggingBackend_File_); ok {
		return x.File
	}
	return nil
}

func (m *LoggingBackend) GetTcp() *LoggingBackend_Tcp {
	if x, ok := m.GetType().(*LoggingBackend_Tcp_); ok {
		return x.Tcp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LoggingBackend) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LoggingBackend_File_)(nil),
		(*LoggingBackend_Tcp_)(nil),
	}
}

// Simple logging to file
type LoggingBackend_File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoggingBackend_File) Reset()         { *m = LoggingBackend_File{} }
func (m *LoggingBackend_File) String() string { return proto.CompactTextString(m) }
func (*LoggingBackend_File) ProtoMessage()    {}
func (*LoggingBackend_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{4, 0}
}

func (m *LoggingBackend_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggingBackend_File.Unmarshal(m, b)
}
func (m *LoggingBackend_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggingBackend_File.Marshal(b, m, deterministic)
}
func (m *LoggingBackend_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggingBackend_File.Merge(m, src)
}
func (m *LoggingBackend_File) XXX_Size() int {
	return xxx_messageInfo_LoggingBackend_File.Size(m)
}
func (m *LoggingBackend_File) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggingBackend_File.DiscardUnknown(m)
}

var xxx_messageInfo_LoggingBackend_File proto.InternalMessageInfo

func (m *LoggingBackend_File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type LoggingBackend_Tcp struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoggingBackend_Tcp) Reset()         { *m = LoggingBackend_Tcp{} }
func (m *LoggingBackend_Tcp) String() string { return proto.CompactTextString(m) }
func (*LoggingBackend_Tcp) ProtoMessage()    {}
func (*LoggingBackend_Tcp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b3cd8c92bbf6a, []int{4, 1}
}

func (m *LoggingBackend_Tcp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggingBackend_Tcp.Unmarshal(m, b)
}
func (m *LoggingBackend_Tcp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggingBackend_Tcp.Marshal(b, m, deterministic)
}
func (m *LoggingBackend_Tcp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggingBackend_Tcp.Merge(m, src)
}
func (m *LoggingBackend_Tcp) XXX_Size() int {
	return xxx_messageInfo_LoggingBackend_Tcp.Size(m)
}
func (m *LoggingBackend_Tcp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggingBackend_Tcp.DiscardUnknown(m)
}

var xxx_messageInfo_LoggingBackend_Tcp proto.InternalMessageInfo

func (m *LoggingBackend_Tcp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Mesh)(nil), "kuma.mesh.v1alpha1.Mesh")
	proto.RegisterType((*Mesh_Mtls)(nil), "kuma.mesh.v1alpha1.Mesh.Mtls")
	proto.RegisterType((*CertificateAuthority)(nil), "kuma.mesh.v1alpha1.CertificateAuthority")
	proto.RegisterType((*CertificateAuthority_Builtin)(nil), "kuma.mesh.v1alpha1.CertificateAuthority.Builtin")
	proto.RegisterType((*Tracing)(nil), "kuma.mesh.v1alpha1.Tracing")
	proto.RegisterType((*Tracing_Zipkin)(nil), "kuma.mesh.v1alpha1.Tracing.Zipkin")
	proto.RegisterType((*Logging)(nil), "kuma.mesh.v1alpha1.Logging")
	proto.RegisterType((*LoggingBackend)(nil), "kuma.mesh.v1alpha1.LoggingBackend")
	proto.RegisterType((*LoggingBackend_File)(nil), "kuma.mesh.v1alpha1.LoggingBackend.File")
	proto.RegisterType((*LoggingBackend_Tcp)(nil), "kuma.mesh.v1alpha1.LoggingBackend.Tcp")
}

func init() { proto.RegisterFile("mesh/v1alpha1/mesh.proto", fileDescriptor_ae9b3cd8c92bbf6a) }

var fileDescriptor_ae9b3cd8c92bbf6a = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x8b, 0xd4, 0x30,
	0x14, 0xc6, 0x67, 0x3a, 0xa1, 0x9d, 0x79, 0xc2, 0x1e, 0x82, 0x48, 0xa9, 0x88, 0x4b, 0x0f, 0xeb,
	0x9e, 0xb2, 0x8e, 0x22, 0x88, 0xa8, 0xe0, 0x08, 0x32, 0x87, 0xdd, 0x4b, 0x98, 0xd3, 0xdc, 0x32,
	0x69, 0x3a, 0x0d, 0x93, 0xb6, 0xb1, 0x4d, 0x95, 0xf5, 0xea, 0xbf, 0xed, 0x41, 0x92, 0x26, 0x03,
	0xea, 0xac, 0xbb, 0xb7, 0xf7, 0x5e, 0xbe, 0xdf, 0xfb, 0x5e, 0x5f, 0x1a, 0x48, 0x6b, 0xd1, 0x57,
	0x57, 0xdf, 0x96, 0x4c, 0xe9, 0x8a, 0x2d, 0xaf, 0x6c, 0x46, 0x74, 0xd7, 0x9a, 0x16, 0xe3, 0xc3,
	0x50, 0x33, 0xe2, 0x0a, 0xe1, 0x38, 0xff, 0x19, 0x01, 0xba, 0x11, 0x7d, 0x85, 0x97, 0x80, 0x6a,
	0xa3, 0xfa, 0x74, 0x7a, 0x3e, 0xbd, 0x7c, 0xf4, 0xea, 0x19, 0xf9, 0x57, 0x4b, 0xac, 0x8e, 0xdc,
	0x18, 0xd5, 0x53, 0x27, 0xc5, 0x6f, 0x20, 0x31, 0x1d, 0xe3, 0xb2, 0xd9, 0xa7, 0x91, 0xa3, 0x9e,
	0x9e, 0xa2, 0x36, 0xa3, 0x84, 0x06, 0xad, 0xc5, 0x54, 0xbb, 0xdf, 0x5b, 0x6c, 0x76, 0x37, 0x76,
	0x3d, 0x4a, 0x68, 0xd0, 0x66, 0x5b, 0x40, 0xd6, 0x1b, 0xbf, 0x85, 0x88, 0x33, 0x3f, 0xe6, 0xe5,
	0x29, 0xf2, 0xb3, 0xe8, 0x8c, 0x2c, 0x25, 0x67, 0x46, 0x7c, 0x1a, 0x4c, 0xd5, 0x76, 0xd2, 0xdc,
	0xd2, 0x88, 0x33, 0x9c, 0x42, 0x22, 0x1a, 0xb6, 0x53, 0xa2, 0x70, 0xf3, 0xce, 0x69, 0x48, 0xf3,
	0xef, 0xf0, 0xf8, 0x14, 0x85, 0xaf, 0x21, 0xd9, 0x0d, 0x52, 0x19, 0xd9, 0x78, 0xc3, 0x97, 0x0f,
	0x35, 0x24, 0xab, 0x91, 0x5b, 0x4f, 0x68, 0x68, 0x91, 0x2d, 0x20, 0xf1, 0xd5, 0x55, 0x0c, 0xc8,
	0xdc, 0x6a, 0x91, 0xf7, 0x90, 0xf8, 0xfd, 0xe0, 0xf7, 0x10, 0xff, 0x90, 0xfa, 0x70, 0xb4, 0xca,
	0xff, 0xb3, 0x4c, 0xb2, 0x75, 0xca, 0xf5, 0x84, 0x7a, 0x26, 0xcb, 0x21, 0x1e, 0x6b, 0xf6, 0x2b,
	0x59, 0x51, 0x74, 0xa2, 0x1f, 0xef, 0x72, 0x41, 0x43, 0x7a, 0x34, 0xfd, 0x0a, 0x89, 0xdf, 0x2e,
	0xbe, 0x80, 0xb3, 0x42, 0x94, 0x6c, 0x50, 0x66, 0xc5, 0xf8, 0x41, 0x34, 0x85, 0x67, 0xfe, 0xaa,
	0xe2, 0x8f, 0x30, 0xdf, 0x8d, 0x61, 0x9f, 0x46, 0xe7, 0xb3, 0xbb, 0xc6, 0xf3, 0x6d, 0x3d, 0x45,
	0x8f, 0x4c, 0xfe, 0x6b, 0x0a, 0x67, 0x7f, 0x1e, 0x62, 0x0c, 0xa8, 0x61, 0xb5, 0xf0, 0x86, 0x2e,
	0xc6, 0x4f, 0x20, 0x2e, 0xdb, 0xae, 0x66, 0xc6, 0x5d, 0xd0, 0x82, 0xfa, 0x0c, 0x7f, 0x00, 0x54,
	0x4a, 0x25, 0xfc, 0xff, 0xf2, 0xe2, 0x7e, 0x6b, 0xf2, 0x45, 0x2a, 0xb1, 0x9e, 0x50, 0x87, 0xe1,
	0x77, 0x30, 0x33, 0x5c, 0xa7, 0xc8, 0xd1, 0x17, 0x0f, 0xa0, 0x37, 0x5c, 0xaf, 0x27, 0xd4, 0x42,
	0x59, 0x06, 0xc8, 0xf6, 0xb2, 0xe3, 0x6a, 0x66, 0xaa, 0x30, 0xae, 0x8d, 0xb3, 0xe7, 0x30, 0xdb,
	0x70, 0x7d, 0xff, 0xc6, 0x57, 0xb0, 0x9d, 0x07, 0xab, 0x5d, 0xec, 0x1e, 0xe3, 0xeb, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xda, 0xa7, 0x36, 0x8e, 0xa8, 0x03, 0x00, 0x00,
}
