// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.20.0
// source: api/mesh/v1alpha1/service_insight.proto

package v1alpha1

import (
	_ "github.com/kumahq/kuma/api/mesh"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceInsight_Service_Status int32

const (
	ServiceInsight_Service_none               ServiceInsight_Service_Status = 0 // should not be used
	ServiceInsight_Service_offline            ServiceInsight_Service_Status = 1
	ServiceInsight_Service_partially_degraded ServiceInsight_Service_Status = 2
	ServiceInsight_Service_online             ServiceInsight_Service_Status = 3
	ServiceInsight_Service_not_available      ServiceInsight_Service_Status = 4
)

// Enum value maps for ServiceInsight_Service_Status.
var (
	ServiceInsight_Service_Status_name = map[int32]string{
		0: "none",
		1: "offline",
		2: "partially_degraded",
		3: "online",
		4: "not_available",
	}
	ServiceInsight_Service_Status_value = map[string]int32{
		"none":               0,
		"offline":            1,
		"partially_degraded": 2,
		"online":             3,
		"not_available":      4,
	}
)

func (x ServiceInsight_Service_Status) Enum() *ServiceInsight_Service_Status {
	p := new(ServiceInsight_Service_Status)
	*p = x
	return p
}

func (x ServiceInsight_Service_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceInsight_Service_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mesh_v1alpha1_service_insight_proto_enumTypes[0].Descriptor()
}

func (ServiceInsight_Service_Status) Type() protoreflect.EnumType {
	return &file_api_mesh_v1alpha1_service_insight_proto_enumTypes[0]
}

func (x ServiceInsight_Service_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceInsight_Service_Status.Descriptor instead.
func (ServiceInsight_Service_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_service_insight_proto_rawDescGZIP(), []int{0, 0, 0}
}

type ServiceInsight_Service_Type int32

const (
	ServiceInsight_Service_internal          ServiceInsight_Service_Type = 0
	ServiceInsight_Service_external          ServiceInsight_Service_Type = 1
	ServiceInsight_Service_gateway_delegated ServiceInsight_Service_Type = 2
	ServiceInsight_Service_gateway_builtin   ServiceInsight_Service_Type = 3
)

// Enum value maps for ServiceInsight_Service_Type.
var (
	ServiceInsight_Service_Type_name = map[int32]string{
		0: "internal",
		1: "external",
		2: "gateway_delegated",
		3: "gateway_builtin",
	}
	ServiceInsight_Service_Type_value = map[string]int32{
		"internal":          0,
		"external":          1,
		"gateway_delegated": 2,
		"gateway_builtin":   3,
	}
)

func (x ServiceInsight_Service_Type) Enum() *ServiceInsight_Service_Type {
	p := new(ServiceInsight_Service_Type)
	*p = x
	return p
}

func (x ServiceInsight_Service_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceInsight_Service_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mesh_v1alpha1_service_insight_proto_enumTypes[1].Descriptor()
}

func (ServiceInsight_Service_Type) Type() protoreflect.EnumType {
	return &file_api_mesh_v1alpha1_service_insight_proto_enumTypes[1]
}

func (x ServiceInsight_Service_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceInsight_Service_Type.Descriptor instead.
func (ServiceInsight_Service_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_service_insight_proto_rawDescGZIP(), []int{0, 0, 1}
}

type ServiceInsight struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Services      map[string]*ServiceInsight_Service `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInsight) Reset() {
	*x = ServiceInsight{}
	mi := &file_api_mesh_v1alpha1_service_insight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInsight) ProtoMessage() {}

func (x *ServiceInsight) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_service_insight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInsight.ProtoReflect.Descriptor instead.
func (*ServiceInsight) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_service_insight_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInsight) GetServices() map[string]*ServiceInsight_Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceInsight_Service struct {
	state          protoimpl.MessageState                `protogen:"open.v1"`
	Status         ServiceInsight_Service_Status         `protobuf:"varint,1,opt,name=status,proto3,enum=kuma.mesh.v1alpha1.ServiceInsight_Service_Status" json:"status,omitempty"`
	Dataplanes     *ServiceInsight_Service_DataplaneStat `protobuf:"bytes,2,opt,name=dataplanes,proto3" json:"dataplanes,omitempty"`
	IssuedBackends map[string]uint32                     `protobuf:"bytes,3,rep,name=issuedBackends,proto3" json:"issuedBackends,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ServiceType    ServiceInsight_Service_Type           `protobuf:"varint,4,opt,name=serviceType,proto3,enum=kuma.mesh.v1alpha1.ServiceInsight_Service_Type" json:"serviceType,omitempty"`
	AddressPort    string                                `protobuf:"bytes,5,opt,name=addressPort,proto3" json:"addressPort,omitempty"`
	Zones          []string                              `protobuf:"bytes,6,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceInsight_Service) Reset() {
	*x = ServiceInsight_Service{}
	mi := &file_api_mesh_v1alpha1_service_insight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInsight_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInsight_Service) ProtoMessage() {}

func (x *ServiceInsight_Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_service_insight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInsight_Service.ProtoReflect.Descriptor instead.
func (*ServiceInsight_Service) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_service_insight_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceInsight_Service) GetStatus() ServiceInsight_Service_Status {
	if x != nil {
		return x.Status
	}
	return ServiceInsight_Service_none
}

func (x *ServiceInsight_Service) GetDataplanes() *ServiceInsight_Service_DataplaneStat {
	if x != nil {
		return x.Dataplanes
	}
	return nil
}

func (x *ServiceInsight_Service) GetIssuedBackends() map[string]uint32 {
	if x != nil {
		return x.IssuedBackends
	}
	return nil
}

func (x *ServiceInsight_Service) GetServiceType() ServiceInsight_Service_Type {
	if x != nil {
		return x.ServiceType
	}
	return ServiceInsight_Service_internal
}

func (x *ServiceInsight_Service) GetAddressPort() string {
	if x != nil {
		return x.AddressPort
	}
	return ""
}

func (x *ServiceInsight_Service) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

type ServiceInsight_Service_DataplaneStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Online        uint32                 `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Offline       uint32                 `protobuf:"varint,3,opt,name=offline,proto3" json:"offline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInsight_Service_DataplaneStat) Reset() {
	*x = ServiceInsight_Service_DataplaneStat{}
	mi := &file_api_mesh_v1alpha1_service_insight_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInsight_Service_DataplaneStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInsight_Service_DataplaneStat) ProtoMessage() {}

func (x *ServiceInsight_Service_DataplaneStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_mesh_v1alpha1_service_insight_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInsight_Service_DataplaneStat.ProtoReflect.Descriptor instead.
func (*ServiceInsight_Service_DataplaneStat) Descriptor() ([]byte, []int) {
	return file_api_mesh_v1alpha1_service_insight_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ServiceInsight_Service_DataplaneStat) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ServiceInsight_Service_DataplaneStat) GetOnline() uint32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *ServiceInsight_Service_DataplaneStat) GetOffline() uint32 {
	if x != nil {
		return x.Offline
	}
	return 0
}

var File_api_mesh_v1alpha1_service_insight_proto protoreflect.FileDescriptor

const file_api_mesh_v1alpha1_service_insight_proto_rawDesc = "" +
	"\n" +
	"'api/mesh/v1alpha1/service_insight.proto\x12\x12kuma.mesh.v1alpha1\x1a\x16api/mesh/options.proto\"\xd5\b\n" +
	"\x0eServiceInsight\x12L\n" +
	"\bservices\x18\x02 \x03(\v20.kuma.mesh.v1alpha1.ServiceInsight.ServicesEntryR\bservices\x1a\xa1\x06\n" +
	"\aService\x12I\n" +
	"\x06status\x18\x01 \x01(\x0e21.kuma.mesh.v1alpha1.ServiceInsight.Service.StatusR\x06status\x12X\n" +
	"\n" +
	"dataplanes\x18\x02 \x01(\v28.kuma.mesh.v1alpha1.ServiceInsight.Service.DataplaneStatR\n" +
	"dataplanes\x12f\n" +
	"\x0eissuedBackends\x18\x03 \x03(\v2>.kuma.mesh.v1alpha1.ServiceInsight.Service.IssuedBackendsEntryR\x0eissuedBackends\x12Q\n" +
	"\vserviceType\x18\x04 \x01(\x0e2/.kuma.mesh.v1alpha1.ServiceInsight.Service.TypeR\vserviceType\x12 \n" +
	"\vaddressPort\x18\x05 \x01(\tR\vaddressPort\x12\x14\n" +
	"\x05zones\x18\x06 \x03(\tR\x05zones\x1aW\n" +
	"\rDataplaneStat\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x16\n" +
	"\x06online\x18\x02 \x01(\rR\x06online\x12\x18\n" +
	"\aoffline\x18\x03 \x01(\rR\aoffline\x1aA\n" +
	"\x13IssuedBackendsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"V\n" +
	"\x06Status\x12\b\n" +
	"\x04none\x10\x00\x12\v\n" +
	"\aoffline\x10\x01\x12\x16\n" +
	"\x12partially_degraded\x10\x02\x12\n" +
	"\n" +
	"\x06online\x10\x03\x12\x11\n" +
	"\rnot_available\x10\x04\"N\n" +
	"\x04Type\x12\f\n" +
	"\binternal\x10\x00\x12\f\n" +
	"\bexternal\x10\x01\x12\x15\n" +
	"\x11gateway_delegated\x10\x02\x12\x13\n" +
	"\x0fgateway_builtin\x10\x03::\xaa\x8c\x89\xa6\x014\n" +
	"\x17ServiceOverviewResource\x12\x0fServiceOverview\"\x04mesh0\x01`\x01\x1ag\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.kuma.mesh.v1alpha1.ServiceInsight.ServiceR\x05value:\x028\x01:b\xaa\x8c\x89\xa6\x01\\\n" +
	"\x16ServiceInsightResource\x12\x0eServiceInsight\"\x04mesh:\x13\n" +
	"\x0fservice-insight\x18\x01R\x17model.GlobalToZonesFlagJ\x04\b\x01\x10\x02B*Z(github.com/kumahq/kuma/api/mesh/v1alpha1b\x06proto3"

var (
	file_api_mesh_v1alpha1_service_insight_proto_rawDescOnce sync.Once
	file_api_mesh_v1alpha1_service_insight_proto_rawDescData []byte
)

func file_api_mesh_v1alpha1_service_insight_proto_rawDescGZIP() []byte {
	file_api_mesh_v1alpha1_service_insight_proto_rawDescOnce.Do(func() {
		file_api_mesh_v1alpha1_service_insight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mesh_v1alpha1_service_insight_proto_rawDesc), len(file_api_mesh_v1alpha1_service_insight_proto_rawDesc)))
	})
	return file_api_mesh_v1alpha1_service_insight_proto_rawDescData
}

var file_api_mesh_v1alpha1_service_insight_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_mesh_v1alpha1_service_insight_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_mesh_v1alpha1_service_insight_proto_goTypes = []any{
	(ServiceInsight_Service_Status)(0),           // 0: kuma.mesh.v1alpha1.ServiceInsight.Service.Status
	(ServiceInsight_Service_Type)(0),             // 1: kuma.mesh.v1alpha1.ServiceInsight.Service.Type
	(*ServiceInsight)(nil),                       // 2: kuma.mesh.v1alpha1.ServiceInsight
	(*ServiceInsight_Service)(nil),               // 3: kuma.mesh.v1alpha1.ServiceInsight.Service
	nil,                                          // 4: kuma.mesh.v1alpha1.ServiceInsight.ServicesEntry
	(*ServiceInsight_Service_DataplaneStat)(nil), // 5: kuma.mesh.v1alpha1.ServiceInsight.Service.DataplaneStat
	nil, // 6: kuma.mesh.v1alpha1.ServiceInsight.Service.IssuedBackendsEntry
}
var file_api_mesh_v1alpha1_service_insight_proto_depIdxs = []int32{
	4, // 0: kuma.mesh.v1alpha1.ServiceInsight.services:type_name -> kuma.mesh.v1alpha1.ServiceInsight.ServicesEntry
	0, // 1: kuma.mesh.v1alpha1.ServiceInsight.Service.status:type_name -> kuma.mesh.v1alpha1.ServiceInsight.Service.Status
	5, // 2: kuma.mesh.v1alpha1.ServiceInsight.Service.dataplanes:type_name -> kuma.mesh.v1alpha1.ServiceInsight.Service.DataplaneStat
	6, // 3: kuma.mesh.v1alpha1.ServiceInsight.Service.issuedBackends:type_name -> kuma.mesh.v1alpha1.ServiceInsight.Service.IssuedBackendsEntry
	1, // 4: kuma.mesh.v1alpha1.ServiceInsight.Service.serviceType:type_name -> kuma.mesh.v1alpha1.ServiceInsight.Service.Type
	3, // 5: kuma.mesh.v1alpha1.ServiceInsight.ServicesEntry.value:type_name -> kuma.mesh.v1alpha1.ServiceInsight.Service
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_mesh_v1alpha1_service_insight_proto_init() }
func file_api_mesh_v1alpha1_service_insight_proto_init() {
	if File_api_mesh_v1alpha1_service_insight_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mesh_v1alpha1_service_insight_proto_rawDesc), len(file_api_mesh_v1alpha1_service_insight_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_mesh_v1alpha1_service_insight_proto_goTypes,
		DependencyIndexes: file_api_mesh_v1alpha1_service_insight_proto_depIdxs,
		EnumInfos:         file_api_mesh_v1alpha1_service_insight_proto_enumTypes,
		MessageInfos:      file_api_mesh_v1alpha1_service_insight_proto_msgTypes,
	}.Build()
	File_api_mesh_v1alpha1_service_insight_proto = out.File
	file_api_mesh_v1alpha1_service_insight_proto_goTypes = nil
	file_api_mesh_v1alpha1_service_insight_proto_depIdxs = nil
}
