workspace(name = "konvoy_filter")

#
# Envoy core extensions to include into the build (must be configured before Envoy)
#

local_repository(
    name = "envoy_build_config",
    # Envoy build config with the most of extensions turned off
    path = "envoy_build_config",
)

#
# Envoy dependencies
#

local_repository(
    name = "envoy",
    path = "envoy",
)

load("@envoy//bazel:api_repositories.bzl", "envoy_api_dependencies")
envoy_api_dependencies()

load("@envoy//bazel:repositories.bzl", "GO_VERSION", "envoy_dependencies")
envoy_dependencies()

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies()

load("@envoy//bazel:cc_configure.bzl", "cc_configure")
cc_configure()

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains(go_version = GO_VERSION)

# Konvoy Filter API dependencies

load("//bazel:api_repositories.bzl", "konvoy_filter_api_dependencies")
konvoy_filter_api_dependencies()
