FROM ubuntu:xenial

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  build-essential \
  libffi-dev \
  lsb-release \
  rpm \
  ruby \
  ruby-dev \
  rubygems

RUN gem install --no-ri --no-rdoc fpm

USER nobody:nogroup
