ARG PARENT_IMAGE="centos:7"

FROM ${PARENT_IMAGE}

RUN mkdir -p /etc/konvoy

COPY usr/bin/konvoy /usr/local/bin/konvoy
COPY etc/konvoy/konvoy-demo.yaml /etc/konvoy/konvoy-demo.yaml

EXPOSE 10000

COPY docker/entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["konvoy", "-c", "/etc/konvoy/konvoy-demo.yaml"]

USER nobody:nobody
