openapi: 3.1.0
info:
  version: v1alpha1
  title: Kuma API
  description: Kuma API
  x-ref-schema-name: "MeshOverview"

paths:
  /meshes/{name}/_overview:
    get:
      operationId: getMeshOverview
      parameters:
        - in: path
          name: name
          required: true
          description: The name of the mesh to get the overview for.
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/GetMeshOverviewResponse'
        '400':
          $ref: '/specs/base/specs/common/error_schema.yaml#/components/responses/BadRequest'
        '500':
          $ref: '/specs/base/specs/common/error_schema.yaml#/components/responses/Internal'
  /meshes/_overview:
    get:
      operationId: getMeshOverviewList
      responses:
        '200':
          $ref: '#/components/responses/GetMeshOverviewListResponse'
        '400':
          $ref: '/specs/base/specs/common/error_schema.yaml#/components/responses/BadRequest'
        '500':
          $ref: '/specs/base/specs/common/error_schema.yaml#/components/responses/Internal'

components:
  schemas:
    MeshOverviewWithMeta:
      allOf:
        - $ref: '/specs/base/specs/common/resource.yaml#/components/schemas/Meta'
        - $ref: '/specs/protoresources/meshoverview/schema.yaml#/components/schemas/MeshOverview'

  responses:
    GetMeshOverviewResponse:
      description: A response containing the overview of a mesh.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MeshOverviewWithMeta'
    GetMeshOverviewListResponse:
      description: A response containing a list of mesh overviews.
      content:
        application/json:
          schema:
            type: object
            properties:
              total:
                type: integer
                example: 200
              next:
                type: string
              items:
                type: array
                items:
                  $ref: '#/components/schemas/MeshOverviewWithMeta'
