package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (cb *Zone) DeepCopyInto(out *Zone) {
	*out = *cb
	out.TypeMeta = cb.TypeMeta
	cb.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = runtime.DeepCopyJSON(cb.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficPermission.
func (cb *Zone) DeepCopy() *Zone {
	if cb == nil {
		return nil
	}
	out := new(Zone)
	cb.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (cb *Zone) DeepCopyObject() runtime.Object {
	if c := cb.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (l *ZoneList) DeepCopyInto(out *ZoneList) {
	*out = *l
	out.TypeMeta = l.TypeMeta
	out.ListMeta = l.ListMeta
	if l.Items != nil {
		in, out := &l.Items, &out.Items
		*out = make([]Zone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficPermissionList.
func (l *ZoneList) DeepCopy() *ZoneList {
	if l == nil {
		return nil
	}
	out := new(ZoneList)
	l.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (l *ZoneList) DeepCopyObject() runtime.Object {
	if c := l.DeepCopy(); c != nil {
		return c
	}
	return nil
}
