# using Envoy's base to copy the Envoy binary
FROM envoyproxy/envoy:v1.18.3 as envoy

FROM ubuntu:20.04

RUN mkdir /kuma
RUN echo "# use this file to override default configuration of \`kuma-cp\`" > /kuma/kuma-cp.conf \
    && chmod a+rw /kuma/kuma-cp.conf

RUN apt update \
  && apt dist-upgrade -y \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  tzdata openssh-server curl ncat vim net-tools iptables iproute2 dnsutils tmux strace tcpdump \
  && rm -rf /var/lib/apt/lists/*

RUN ssh-keygen -A \
  && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
  && sed -i s/#PermitEmptyPasswords.*/PermitEmptyPasswords\ yes/ /etc/ssh/sshd_config \
  && mkdir /var/run/sshd \
  && passwd -d root \
  && chmod a+rwx /root \
  && useradd -U kuma-dp

COPY --from=envoy /usr/local/bin/envoy /usr/local/bin/envoy

ADD $KUMA_ROOT/build/artifacts-linux-amd64/kuma-cp/kuma-cp /usr/bin
ADD $KUMA_ROOT/build/artifacts-linux-amd64/kuma-dp/kuma-dp /usr/bin
ADD $KUMA_ROOT/build/artifacts-linux-amd64/coredns/coredns /usr/bin
ADD $KUMA_ROOT/build/artifacts-linux-amd64/kumactl/kumactl /usr/bin
ADD $KUMA_ROOT/build/artifacts-linux-amd64/test-server/test-server /usr/bin

# do not detach (-D), log to stderr (-e)
CMD ["/usr/sbin/sshd", "-D", "-e"]
