ARG PARENT_IMAGE="frolvlad/alpine-glibc:alpine-3.7"

FROM ${PARENT_IMAGE}

RUN apk update \
  && apk add ca-certificates \
  && update-ca-certificates

RUN mkdir -p /etc/konvoy

COPY usr/bin/konvoy /usr/local/bin/konvoy
COPY etc/konvoy/konvoy-demo.yaml /etc/konvoy/konvoy-demo.yaml

EXPOSE 10000

COPY docker/entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["konvoy", "-c", "/etc/konvoy/konvoy-demo.yaml"]

USER nobody:nogroup
