{
 "title": "Consul Mesh Metrics",
 "description": "Envoy stats",
 "tags": [
  "consul",
  "envoy"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "consul_source_datacenter",
    "query": {
     "query": "label_values(envoy_cluster_version,consul_source_datacenter)"
    }
   },
   {
    "name": "local_cluster",
    "query": {
     "query": "label_values(envoy_server_live{consul_source_datacenter=\"$consul_source_datacenter\"},local_cluster)"
    }
   },
   {
    "name": "consul_destination_target",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_time_bucket{consul_source_datacenter=\"$consul_source_datacenter\",local_cluster=\"$local_cluster\"},consul_destination_target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=https://cncf-branding.netlify.app/img/projects/envoy/stacked/color/envoy-stacked-color.png />"
   }
  },
  {
   "title": "server live",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_server_live{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "days until first cert expiring",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_server_days_until_first_cert_expiring{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Listener statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "LDS update time",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_listener_manager_lds_update_time{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"} ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total listeners",
   "type": "stat",
   "description": "Sum of all listeners ",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_listener_manager_total_listeners_active{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} ) by (consul_source_datacenter) ",
     "legendFormat": "{{consul_source_datacenter}} : {{local_cluster}}"
    }
   ]
  },
  {
   "title": "Listener manager",
   "type": "timeseries",
   "description": "Total listeners added (either via static config or LDS).\nTotal listeners modified (via LDS).\nTotal listeners removed (via LDS).\nTotal listeners stopped.\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_listener_manager_listener_added{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} != 0",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} : added"
    },
    {
     "expr": "envoy_listener_manager_listener_modified{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"}  != 0",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} : modified"
    },
    {
     "expr": "envoy_listener_manager_listener_removed{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"}  != 0",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} : removed"
    },
    {
     "expr": "envoy_listener_manager_listener_stopped{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"}  != 0",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} : stopped"
    }
   ]
  },
  {
   "title": "Connections rejected by overload",
   "type": "timeseries",
   "description": "Total connections rejected due to configured overload actions\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_cx_overload_reject{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"}[$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} "
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Total active connections\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_cx_total{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"}[$__interval]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} : all"
    },
    {
     "expr": "rate(envoy_listener_downstream_cx_destroy{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"}[$__interval]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} : destroy"
    }
   ]
  },
  {
   "title": "Connections no filter chain",
   "type": "timeseries",
   "description": "Total connections that didn’t match any filter chain\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_no_filter_chain_match{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"}[$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} "
    }
   ]
  },
  {
   "title": "Connections rejected by global limit",
   "type": "timeseries",
   "description": "Total connections rejected due to enforcement of global connection limit\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_global_cx_overflow{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"}[$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} "
    }
   ]
  },
  {
   "title": "Sockets filter processing",
   "type": "timeseries",
   "description": "Sockets currently undergoing listener filter processing\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "envoy_listener_downstream_pre_cx_active{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"}",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} "
    }
   ]
  },
  {
   "title": "Sockets that timed out",
   "type": "timeseries",
   "description": "Sockets that timed out during listener filter processing\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_pre_cx_timeout{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"}[$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} : {{consul_source_service}} : {{envoy_http_conn_manager_prefix}} {{envoy_listener_address}} "
    }
   ]
  },
  { "title": "Cluster statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CDS update time",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_cluster_manager_cds_update_time{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\"} ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total clusters",
   "type": "stat",
   "description": "Sum of all clusters",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_manager_active_clusters{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} ) by (consul_source_datacenter) ",
     "legendFormat": "{{consul_source_datacenter}} : {{local_cluster}}"
    }
   ]
  },
  {
   "title": "Cluster membership status",
   "type": "timeseries",
   "description": "Current healthy/degraded/excluded members\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_cluster_membership_degraded{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\",consul_destination_target=~\"^$consul_destination_target$\"} != 0",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{envoy_cluster_name}} : degraded"
    },
    {
     "expr": "envoy_cluster_membership_excluded{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\",consul_destination_target=~\"^$consul_destination_target$\"} != 0",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{envoy_cluster_name}} : excluded"
    },
    {
     "expr": "envoy_cluster_membership_healthy{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\",consul_destination_target=~\"^$consul_destination_target$\"} != 0",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{envoy_cluster_name}} : healthy"
    }
   ]
  },
  {
   "title": "Outlier detection ejected hosts",
   "type": "timeseries",
   "description": "Number of currently ejected hosts\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#outlier-detection-statistics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_active{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\"}",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} ? {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Outlier detection consecutive 5xx ejections",
   "type": "timeseries",
   "description": "Number of enforced consecutive 5xx ejections\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#outlier-detection-statistics",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_outlier_detection_ejections_enforced_consecutive_5xx{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\"}[$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} ? {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Outlier detection consecutive gateway failure",
   "type": "timeseries",
   "description": "Number of enforced consecutive  gateway failure ejections\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#outlier-detection-statistics",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_outlier_detection_ejections_enforced_consecutive_gateway_failure{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\"}[$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} ? {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection active ",
   "type": "timeseries",
   "description": "Total active connections\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\",consul_destination_target!=\"\",consul_destination_target=~\"^$consul_destination_target$\"}",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : rx"
    }
   ]
  },
  {
   "title": "Connection closed",
   "type": "timeseries",
   "description": "Total connections closed via HTTP/1.1 connection close header or HTTP/2 or HTTP/3 GOAWAY\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(envoy_cluster_upstream_cx_close_notify{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"}[1m])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}}"
    }
   ]
  },
  {
   "title": "Connection failures",
   "type": "timeseries",
   "description": "Total connection failures\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_cx_connect_fail{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : failures"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "timeseries",
   "description": "Total connection connect/idle timeouts\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_cx_connect_timeout{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : connect timeout"
    },
    {
     "expr": "increase(envoy_cluster_upstream_cx_idle_timeout{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : idle timeout"
    }
   ]
  },
  {
   "title": "Connection consecutive failures",
   "type": "timeseries",
   "description": "Total consecutive connection failures exceeding configured connection attempts\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(envoy_cluster_upstream_cx_connect_attempts_exceeded{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"}[1m])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}}"
    }
   ]
  },
  {
   "title": "Connection destroyed ",
   "type": "timeseries",
   "description": "Total destroyed connections\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_cx_destroy{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} "
    }
   ]
  },
  {
   "title": "Connection destroyed local",
   "type": "timeseries",
   "description": "Total destroyed local connections\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_cx_destroy_local{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : local"
    },
    {
     "expr": "increase(envoy_cluster_upstream_cx_destroy_local_with_active_rq{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : local_with_active_rq"
    }
   ]
  },
  {
   "title": "Connection destroyed remote",
   "type": "timeseries",
   "description": "Total destroyed remote connections\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_cx_destroy_remote{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : remote"
    },
    {
     "expr": "increase(envoy_cluster_upstream_cx_destroy_remote_with_active_rq{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : remote_with_active_rq"
    }
   ]
  },
  {
   "title": "Connection not established no healthy hosts ",
   "type": "timeseries",
   "description": "Total times connection not established due to no healthy hosts\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_cx_none_healthy{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} "
    }
   ]
  },
  {
   "title": "Connection protocol errors",
   "type": "timeseries",
   "description": "Total connection protocol errors\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_cx_protocol_error{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"} [1m]) ",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} "
    }
   ]
  },
  {
   "title": "Connection transmit bytes",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#arch-overview-outlier-detection",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_tx_bytes_total{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\",consul_destination_target!=\"\",consul_destination_target=~\"^$consul_destination_target$\"} [$__interval:])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : rx"
    }
   ]
  },
  {
   "title": "Connection sent bytes",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#arch-overview-outlier-detection",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_rx_bytes_total{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"$local_cluster\",consul_destination_target!=\"\",consul_destination_target=~\"^$consul_destination_target$\"} [$__interval:])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : rx"
    }
   ]
  },
  {
   "title": "Request total",
   "type": "timeseries",
   "description": "rate of Total requests\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq_total{consul_destination_target!=\"\",consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} [$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} -> {{consul_destination_target}}"
    }
   ]
  },
  {
   "title": "Request active ",
   "type": "timeseries",
   "description": "Total active requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\"}) by (consul_source_datacenter,consul_source_service,kubernetes_pod_name,envoy_cluster_name)",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} ? {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Request timeouts",
   "type": "timeseries",
   "description": "Total requests that timed out waiting for a response\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq_timeout{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} [$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} -> {{consul_destination_target}}"
    }
   ]
  },
  {
   "title": "Request completed",
   "type": "timeseries",
   "description": "Total upstream requests completed\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq_completed{consul_destination_target!=\"\",consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} [$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} -> {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Request cancelled",
   "type": "timeseries",
   "description": "Total requests cancelled before obtaining a connection pool connection\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq_cancelled{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} [$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} -> {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Request closed max duration reached",
   "type": "timeseries",
   "description": "Total requests closed due to max duration reached\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_upstream_rq_max_duration_reached{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\"} [$__interval])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} -> {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Request pending",
   "type": "timeseries",
   "description": "Total requests pending a connection pool connection\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(envoy_cluster_upstream_rq_pending_total{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"}[1m])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}}"
    }
   ]
  },
  {
   "title": "Request pending failure eject",
   "type": "timeseries",
   "description": "Total requests that were failed due to a connection pool connection failure or remote connection termination\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(envoy_cluster_upstream_rq_pending_failure_eject{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"}[1m])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}}"
    }
   ]
  },
  {
   "title": "Request pending overwflow",
   "type": "timeseries",
   "description": "Total requests that overflowed connection pool or requests (mainly for HTTP/2 and above) circuit breaking and were failed\nhttps://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(envoy_cluster_upstream_rq_pending_overflow{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"}[1m])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}}"
    }
   ]
  },
  {
   "title": "Ext upstream requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_external_upstream_rq{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"}[$__interval]) != 0",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} ? {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Ext upstream req time : $consul_destination_target",
   "type": "heatmap",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_bucket{consul_source_datacenter=~\"^$consul_source_datacenter$\",local_cluster=~\"^$local_cluster$\",consul_full_target!=\"\",consul_destination_target=~\"^$consul_destination_target$\",consul_destination_target!=\"\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "gRPC statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Successful service/method calls",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_stats_filter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(label_replace({consul_source_datacenter=~\"$consul_source_datacenter\",consul_full_target!=\"\",__name__=~\"envoy_cluster_grpc_.+_success\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\") [$__interval:])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : {{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "Failed service/method calls",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_stats_filter",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(label_replace({consul_source_datacenter=~\"$consul_source_datacenter\",consul_full_target!=\"\",__name__=~\"envoy_cluster_grpc_.+_failure\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\") [$__interval:])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{consul_destination_target}} : {{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "Request message count for service/method calls",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_stats_filter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(label_replace({consul_source_datacenter=~\"$consul_source_datacenter\",consul_full_target!=\"\",__name__=~\"envoy_cluster_grpc_.+_request_message_count\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\") [$__interval:])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{envoy_cluster_name}} : {{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "Response message count for service/method calls",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_stats_filter",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(label_replace({consul_source_datacenter=~\"$consul_source_datacenter\",consul_full_target!=\"\",__name__=~\"envoy_cluster_grpc_.+_response_message_count\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\") [$__interval:])",
     "legendFormat": "{{consul_source_datacenter}} : {{kubernetes_pod_name}} → {{envoy_cluster_name}} : {{envoy_grpc_bridge_method}}"
    }
   ]
  }
 ]
}