# using Envoy's base to inherit the Envoy binary
FROM envoyproxy/envoy-alpine:v1.16.0

ADD $KUMA_ROOT/build/artifacts-linux-amd64/kuma-dp/kuma-dp /usr/bin

RUN mkdir /kuma
COPY $KUMA_ROOT/tools/releases/templates/LICENSE /kuma
COPY $KUMA_ROOT/tools/releases/templates/NOTICE /kuma
COPY $KUMA_ROOT/tools/releases/templates/README /kuma

RUN echo kuma-dp:x:31337: >> /etc/group
RUN echo kuma-dp:x:31337:31337:kuma-dp:/nonexistent:/sbin/nologin >> /etc/passwd

USER root:root

ENTRYPOINT ["kuma-dp"]
