FROM alpine:3.13.5

ADD $KUMA_ROOT/build/artifacts-linux-amd64/kuma-cp/kuma-cp /usr/bin

RUN mkdir -p /etc/kuma
ADD $KUMA_ROOT/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml /etc/kuma

RUN mkdir /kuma
COPY $KUMA_ROOT/tools/releases/templates/LICENSE /kuma
COPY $KUMA_ROOT/tools/releases/templates/NOTICE /kuma
COPY $KUMA_ROOT/tools/releases/templates/README /kuma

USER nobody:nobody

ENTRYPOINT ["kuma-cp"]
