FROM alpine:3.15.0

ADD $KUMA_ROOT/build/artifacts-linux-amd64/kuma-cp/kuma-cp /usr/bin

RUN mkdir -p /etc/kuma
ADD $KUMA_ROOT/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml /etc/kuma

COPY $KUMA_ROOT/tools/releases/templates/LICENSE \
    $KUMA_ROOT/tools/releases/templates/README \
    /kuma/

COPY $KUMA_ROOT/tools/releases/templates/NOTICE /kuma/

RUN addgroup -S -g 6789 kuma-cp \
 && adduser -S -D -G kuma-cp -u 6789 kuma-cp

USER kuma-cp
WORKDIR /home/kuma-cp

ENTRYPOINT ["kuma-cp"]
