ARG BASE_IMAGE_ARCH=amd64
FROM --platform=linux/$BASE_IMAGE_ARCH kumahq/static-debian11

ARG ARCH
COPY /build/artifacts-linux-$ARCH/kuma-cp/kuma-cp /usr/bin

WORKDIR /home/kuma-cp

ENTRYPOINT ["kuma-cp"]
