FROM alpine:3.15.2

ARG ARCH

ADD $KUMA_ROOT/build/artifacts-linux-$ARCH/kuma-prometheus-sd/kuma-prometheus-sd /usr/bin

COPY $KUMA_ROOT/tools/releases/templates/LICENSE \
    $KUMA_ROOT/tools/releases/templates/README \
    /kuma/

COPY $KUMA_ROOT/tools/releases/templates/NOTICE /kuma/

USER nobody:nobody

ENTRYPOINT ["kuma-prometheus-sd"]
