# we use this file to copy only relevant artifcats to the context, see tools/releases/copy-image-artifacts.sh:33
*
!build/artifacts-linux-amd64/kumactl/kumactl
!build/artifacts-linux-arm64/kumactl/kumactl
!build/artifacts-darwin-amd64/kumactl/kumactl
!build/artifacts-darwin-arm64/kumactl/kumactl
!tools/releases/templates/LICENSE
!tools/releases/templates/NOTICE-kumactl
!tools/releases/templates/README
