ARG BASE_IMAGE_ARCH=amd64
FROM --platform=linux/$BASE_IMAGE_ARCH gcr.io/distroless/static-debian11:debug-nonroot

COPY /tools/releases/templates/LICENSE \
    /tools/releases/templates/README \
    /tools/releases/templates/NOTICE \
    /kuma/
