FROM kumahq/base-debian11:no-push
ARG ARCH

COPY /tools/releases/templates/NOTICE-kumactl /kuma/NOTICE
COPY /build/artifacts-linux-$ARCH/kumactl/kumactl /usr/bin/
# copy static curl
COPY --from=tarampampam/curl:7.78.0 /bin/curl /usr/bin/curl
