# we use this file to copy only relevant artifcats to the context, see tools/releases/copy-image-artifacts.sh:33
*
!build/artifacts-linux-amd64/kuma-cp/kuma-cp
!build/artifacts-linux-arm64/kuma-cp/kuma-cp
!build/artifacts-darwin-arm64/kuma-cp/kuma-cp
!pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
!tools/releases/templates/LICENSE
!tools/releases/templates/NOTICE
!tools/releases/templates/README
