FROM bitnami/kubectl:1.18.8

USER root

RUN addgroup --system --gid 6789 kumactl \
 && adduser --system --disabled-password --ingroup kumactl --uid 6789 kumactl

ADD $KUMA_ROOT/build/artifacts-linux-amd64/kumactl/kumactl /usr/bin

RUN mkdir /kuma
COPY $KUMA_ROOT/tools/releases/templates/LICENSE /kuma
COPY $KUMA_ROOT/tools/releases/templates/NOTICE /kuma
COPY $KUMA_ROOT/tools/releases/templates/README /kuma
COPY --chown=kumactl $KUMA_ROOT/tools/releases/templates/install_missing_crds.sh /kuma
# As the flag `--chmod` is not yet available everywhere we'll temporarily use
# the instruction below, which should be removed in the future
RUN chmod 0544 /kuma/install_missing_crds.sh

ENV HOME /home/kumactl

USER kumactl

WORKDIR /home/kumactl

ENTRYPOINT ["/bin/sh"]
