FROM docker.io/istio/proxy_init:1.1.2

RUN mkdir /kuma
COPY $KUMA_ROOT/tools/releases/templates/LICENSE /kuma
COPY $KUMA_ROOT/tools/releases/templates/NOTICE /kuma
COPY $KUMA_ROOT/tools/releases/templates/README /kuma