FROM bitnami/kubectl:1.18.8

USER root

RUN addgroup --system --gid 6789 kumactl \
 && adduser --system --disabled-password --ingroup kumactl --uid 6789 kumactl

ADD $KUMA_ROOT/build/artifacts-linux-amd64/kumactl/kumactl /usr/bin

RUN mkdir /kuma
COPY $KUMA_ROOT/tools/releases/templates/LICENSE /kuma
COPY $KUMA_ROOT/tools/releases/templates/NOTICE /kuma
COPY $KUMA_ROOT/tools/releases/templates/README /kuma
COPY --chown=kumactl --chmod=544 $KUMA_ROOT/tools/releases/templates/install_missing_crds.sh /kuma

ENV HOME /home/kumactl

USER kumactl

WORKDIR /home/kumactl

ENTRYPOINT ["/bin/sh"]
