FROM gcr.io/distroless/preview/base-nossl-debian11:debug-nonroot-amd64

COPY /tools/releases/templates/LICENSE \
    /tools/releases/templates/README \
    /tools/releases/templates/NOTICE \
    /kuma/
