*
!build/artifacts-linux-amd64/kuma-cni/kuma-cni
!build/artifacts-linux-amd64/kuma-cni/kuma-cni-install
!tools/releases/templates/LICENSE
!tools/releases/templates/NOTICE-kumactl
!tools/releases/templates/README
