FROM kumahq/static-debian11:1.0.0

ARG ARCH
COPY /build/artifacts-linux-$ARCH/kuma-cni/kuma-cni /opt/cni/bin/kuma-cni
COPY /build/artifacts-linux-$ARCH/install-cni/install-cni /install-cni

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
ENTRYPOINT [ "/install-cni" ]
