*
!build/artifacts-linux-amd64/kumactl/kumactl
!build/artifacts-linux-arm64/kumactl/kumactl
!tools/releases/templates/LICENSE
!tools/releases/templates/NOTICE-kumactl
!tools/releases/templates/README
!tools/releases/templates/install_missing_crds.sh
