FROM envoyproxy/envoy:latest

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    iproute2 \
    iptables \
    netcat \
    curl \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -m --uid 1337 envoy
