## build image
FROM golang:1.12.5
ENV GO111MODULE=on

WORKDIR /go/src/github.com/Kong/kuma/components/konvoy-control-plane

# facilitate docker layer caching
COPY go.mod go.mod
COPY go.sum go.sum
COPY api/go.mod api/go.mod
COPY api/go.sum api/go.sum
COPY pkg/plugins/resources/k8s/native/go.mod pkg/plugins/resources/k8s/native/go.mod
COPY pkg/plugins/resources/k8s/native/go.sum pkg/plugins/resources/k8s/native/go.sum

RUN go mod download

COPY . .

RUN make build/kuma-injector

## runtime image
FROM alpine:latest

ENV PATH=$PATH:/kuma-injector
COPY --from=0 /go/src/github.com/Kong/kuma/components/konvoy-control-plane/build/artifacts/kuma-injector/kuma-injector /kuma-injector/kuma-injector

RUN addgroup -S -g 5678 kuma-injector \
 && adduser -S -D -G kuma-injector -u 5678 kuma-injector

USER kuma-injector

ENTRYPOINT ["kuma-injector"]
CMD ["run"]
