## build image
FROM golang:1.12.5
ENV GO111MODULE=on

WORKDIR /go/src/github.com/Kong/konvoy/components/konvoy-control-plane

# facilitate docker layer caching
COPY go.mod go.mod
COPY go.sum go.sum
COPY api/go.mod api/go.mod
COPY api/go.sum api/go.sum
COPY pkg/plugins/resources/k8s/native/go.mod pkg/plugins/resources/k8s/native/go.mod
COPY pkg/plugins/resources/k8s/native/go.sum pkg/plugins/resources/k8s/native/go.sum

RUN go mod download

COPY . .

RUN make build/kuma-dp

## runtime image
FROM envoyproxy/envoy-alpine:latest

ENV PATH=$PATH:/kuma-dataplane
COPY --from=0 /go/src/github.com/Kong/konvoy/components/konvoy-control-plane/build/artifacts/kuma-dataplane/kuma-dataplane /kuma-dataplane/kuma-dataplane

RUN addgroup -S -g 5678 kuma-dataplane \
 && adduser -S -D -G kuma-dataplane -u 5678 kuma-dataplane

USER kuma-dataplane

ENTRYPOINT ["kuma-dataplane"]
CMD ["run"]
