// Generated by tools/policy-gen. DO NOT EDIT.
// Run "make generate" to update this file.

package v1alpha1

import (
	_ "embed"
	"fmt"

	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apiextensions-apiserver/pkg/apiserver/schema"
	"k8s.io/kube-openapi/pkg/validation/strfmt"
	"k8s.io/kube-openapi/pkg/validation/validate"
	"sigs.k8s.io/yaml"

	"github.com/kumahq/kuma/v2/pkg/core/resources/apis/core"
	"github.com/kumahq/kuma/v2/pkg/core/resources/model"
)

//go:embed rest.yaml
var rawOpenAPISpec []byte

func init() {
	var structuralSchema *schema.Structural
	var v1JsonSchemaProps *apiextensionsv1.JSONSchemaProps
	var validator *validate.SchemaValidator
	if rawOpenAPISpec != nil {
		// Parse OpenAPI spec to extract the schema

		var openapiSpec map[string]interface{}
		if err := yaml.Unmarshal(rawOpenAPISpec, &openapiSpec); err != nil {
			panic(err)
		}

		// Extract schema from .components.schemas.MeshServiceItem
		components, ok := openapiSpec["components"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("components not found in OpenAPI spec"))
		}
		schemas, ok := components["schemas"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("schemas not found in components"))
		}
		schemaItem, ok := schemas["MeshServiceItem"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("MeshServiceItem schema not found"))
		}

		// Marshal the extracted schema back to YAML to unmarshal into JSONSchemaProps
		schemaBytes, err := yaml.Marshal(schemaItem)
		if err != nil {
			panic(err)
		}

		if err := yaml.Unmarshal(schemaBytes, &v1JsonSchemaProps); err != nil {
			panic(err)
		}
		var jsonSchemaProps apiextensions.JSONSchemaProps
		err = apiextensionsv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(v1JsonSchemaProps, &jsonSchemaProps, nil)
		if err != nil {
			panic(err)
		}
		structuralSchema, err = schema.NewStructural(&jsonSchemaProps)
		if err != nil {
			panic(err)
		}
		schemaObject := structuralSchema.ToKubeOpenAPI()
		validator = validate.NewSchemaValidator(schemaObject, nil, "", strfmt.Default)
	}
	rawOpenAPISpec = nil
	MeshServiceResourceTypeDescriptor.Validator = validator
	MeshServiceResourceTypeDescriptor.StructuralSchema = structuralSchema
}

const (
	MeshServiceType model.ResourceType = "MeshService"
)

var _ model.Resource = &MeshServiceResource{}

type MeshServiceResource struct {
	Meta   model.ResourceMeta
	Spec   *MeshService
	Status *MeshServiceStatus
}

func NewMeshServiceResource() *MeshServiceResource {
	return &MeshServiceResource{
		Spec:   &MeshService{},
		Status: &MeshServiceStatus{},
	}
}

func (t *MeshServiceResource) GetMeta() model.ResourceMeta {
	return t.Meta
}

func (t *MeshServiceResource) SetMeta(m model.ResourceMeta) {
	t.Meta = m
}

func (t *MeshServiceResource) GetSpec() model.ResourceSpec {
	return t.Spec
}

func (t *MeshServiceResource) SetSpec(spec model.ResourceSpec) error {
	protoType, ok := spec.(*MeshService)
	if !ok {
		return fmt.Errorf("invalid type %T for Spec", spec)
	} else {
		if protoType == nil {
			t.Spec = &MeshService{}
		} else {
			t.Spec = protoType
		}
		return nil
	}
}

func (t *MeshServiceResource) GetStatus() model.ResourceStatus {
	return t.Status
}

func (t *MeshServiceResource) SetStatus(status model.ResourceStatus) error {
	protoType, ok := status.(*MeshServiceStatus)
	if !ok {
		return fmt.Errorf("invalid type %T for Status", status)
	} else {
		if protoType == nil {
			t.Status = &MeshServiceStatus{}
		} else {
			t.Status = protoType
		}
		return nil
	}
}

func (t *MeshServiceResource) Descriptor() model.ResourceTypeDescriptor {
	return MeshServiceResourceTypeDescriptor
}

func (t *MeshServiceResource) Validate() error {
	if v, ok := interface{}(t).(interface{ validate() error }); !ok {
		return nil
	} else {
		return v.validate()
	}
}

var _ model.ResourceList = &MeshServiceResourceList{}

type MeshServiceResourceList struct {
	Items      []*MeshServiceResource
	Pagination model.Pagination
}

func (l *MeshServiceResourceList) GetItems() []model.Resource {
	res := make([]model.Resource, len(l.Items))
	for i, elem := range l.Items {
		res[i] = elem
	}
	return res
}

func (l *MeshServiceResourceList) GetItemType() model.ResourceType {
	return MeshServiceType
}

func (l *MeshServiceResourceList) NewItem() model.Resource {
	return NewMeshServiceResource()
}

func (l *MeshServiceResourceList) AddItem(r model.Resource) error {
	if trr, ok := r.(*MeshServiceResource); ok {
		l.Items = append(l.Items, trr)
		return nil
	} else {
		return model.ErrorInvalidItemType((*MeshServiceResource)(nil), r)
	}
}

func (l *MeshServiceResourceList) GetPagination() *model.Pagination {
	return &l.Pagination
}

func (l *MeshServiceResourceList) SetPagination(p model.Pagination) {
	l.Pagination = p
}

var _ core.Destination = &MeshServiceResource{}

var MeshServiceResourceTypeDescriptor = model.ResourceTypeDescriptor{
	Name:                         MeshServiceType,
	Resource:                     NewMeshServiceResource(),
	ResourceList:                 &MeshServiceResourceList{},
	Scope:                        model.ScopeMesh,
	KDSFlags:                     model.ZoneToGlobalFlag | model.SyncedAcrossZonesFlag,
	WsPath:                       "meshservices",
	KumactlArg:                   "meshservice",
	KumactlListArg:               "meshservices",
	AllowToInspect:               false,
	IsPolicy:                     false,
	IsDestination:                true,
	IsExperimental:               false,
	SingularDisplayName:          "Mesh Service",
	PluralDisplayName:            "Mesh Services",
	IsPluginOriginated:           true,
	IsTargetRefBased:             false,
	HasToTargetRef:               false,
	HasFromTargetRef:             false,
	HasRulesTargetRef:            false,
	HasStatus:                    true,
	AllowedOnSystemNamespaceOnly: false,
	ShortName:                    "msvc",
	IsFromAsRules:                false,
}
