// Generated by tools/policy-gen. DO NOT EDIT.
// Run "make generate" to update this file.

package v1alpha1

import (
	_ "embed"
	"fmt"

	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apiextensions-apiserver/pkg/apiserver/schema"
	"k8s.io/kube-openapi/pkg/validation/strfmt"
	"k8s.io/kube-openapi/pkg/validation/validate"
	"sigs.k8s.io/yaml"

	"github.com/kumahq/kuma/v2/pkg/core/resources/model"
)

//go:embed rest.yaml
var rawOpenAPISpec []byte

func init() {
	var structuralSchema *schema.Structural
	var v1JsonSchemaProps *apiextensionsv1.JSONSchemaProps
	var validator *validate.SchemaValidator
	if rawOpenAPISpec != nil {
		// Parse OpenAPI spec to extract the schema

		var openapiSpec map[string]interface{}
		if err := yaml.Unmarshal(rawOpenAPISpec, &openapiSpec); err != nil {
			panic(err)
		}

		// Extract schema from .components.schemas.WorkloadItem
		components, ok := openapiSpec["components"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("components not found in OpenAPI spec"))
		}
		schemas, ok := components["schemas"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("schemas not found in components"))
		}
		schemaItem, ok := schemas["WorkloadItem"].(map[string]interface{})
		if !ok {
			panic(fmt.Errorf("WorkloadItem schema not found"))
		}

		// Marshal the extracted schema back to YAML to unmarshal into JSONSchemaProps
		schemaBytes, err := yaml.Marshal(schemaItem)
		if err != nil {
			panic(err)
		}

		if err := yaml.Unmarshal(schemaBytes, &v1JsonSchemaProps); err != nil {
			panic(err)
		}
		var jsonSchemaProps apiextensions.JSONSchemaProps
		err = apiextensionsv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(v1JsonSchemaProps, &jsonSchemaProps, nil)
		if err != nil {
			panic(err)
		}
		structuralSchema, err = schema.NewStructural(&jsonSchemaProps)
		if err != nil {
			panic(err)
		}
		schemaObject := structuralSchema.ToKubeOpenAPI()
		validator = validate.NewSchemaValidator(schemaObject, nil, "", strfmt.Default)
	}
	rawOpenAPISpec = nil
	WorkloadResourceTypeDescriptor.Validator = validator
	WorkloadResourceTypeDescriptor.StructuralSchema = structuralSchema
}

const (
	WorkloadType model.ResourceType = "Workload"
)

var _ model.Resource = &WorkloadResource{}

type WorkloadResource struct {
	Meta   model.ResourceMeta
	Spec   *Workload
	Status *WorkloadStatus
}

func NewWorkloadResource() *WorkloadResource {
	return &WorkloadResource{
		Spec:   &Workload{},
		Status: &WorkloadStatus{},
	}
}

func (t *WorkloadResource) GetMeta() model.ResourceMeta {
	return t.Meta
}

func (t *WorkloadResource) SetMeta(m model.ResourceMeta) {
	t.Meta = m
}

func (t *WorkloadResource) GetSpec() model.ResourceSpec {
	return t.Spec
}

func (t *WorkloadResource) SetSpec(spec model.ResourceSpec) error {
	protoType, ok := spec.(*Workload)
	if !ok {
		return fmt.Errorf("invalid type %T for Spec", spec)
	} else {
		if protoType == nil {
			t.Spec = &Workload{}
		} else {
			t.Spec = protoType
		}
		return nil
	}
}

func (t *WorkloadResource) GetStatus() model.ResourceStatus {
	return t.Status
}

func (t *WorkloadResource) SetStatus(status model.ResourceStatus) error {
	protoType, ok := status.(*WorkloadStatus)
	if !ok {
		return fmt.Errorf("invalid type %T for Status", status)
	} else {
		if protoType == nil {
			t.Status = &WorkloadStatus{}
		} else {
			t.Status = protoType
		}
		return nil
	}
}

func (t *WorkloadResource) Descriptor() model.ResourceTypeDescriptor {
	return WorkloadResourceTypeDescriptor
}

func (t *WorkloadResource) Validate() error {
	if v, ok := interface{}(t).(interface{ validate() error }); !ok {
		return nil
	} else {
		return v.validate()
	}
}

var _ model.ResourceList = &WorkloadResourceList{}

type WorkloadResourceList struct {
	Items      []*WorkloadResource
	Pagination model.Pagination
}

func (l *WorkloadResourceList) GetItems() []model.Resource {
	res := make([]model.Resource, len(l.Items))
	for i, elem := range l.Items {
		res[i] = elem
	}
	return res
}

func (l *WorkloadResourceList) GetItemType() model.ResourceType {
	return WorkloadType
}

func (l *WorkloadResourceList) NewItem() model.Resource {
	return NewWorkloadResource()
}

func (l *WorkloadResourceList) AddItem(r model.Resource) error {
	if trr, ok := r.(*WorkloadResource); ok {
		l.Items = append(l.Items, trr)
		return nil
	} else {
		return model.ErrorInvalidItemType((*WorkloadResource)(nil), r)
	}
}

func (l *WorkloadResourceList) GetPagination() *model.Pagination {
	return &l.Pagination
}

func (l *WorkloadResourceList) SetPagination(p model.Pagination) {
	l.Pagination = p
}

var WorkloadResourceTypeDescriptor = model.ResourceTypeDescriptor{
	Name:                         WorkloadType,
	Resource:                     NewWorkloadResource(),
	ResourceList:                 &WorkloadResourceList{},
	Scope:                        model.ScopeMesh,
	KDSFlags:                     model.ZoneToGlobalFlag,
	WsPath:                       "workloads",
	KumactlArg:                   "workload",
	KumactlListArg:               "workloads",
	AllowToInspect:               false,
	IsPolicy:                     false,
	IsDestination:                false,
	IsExperimental:               false,
	SingularDisplayName:          "Workload",
	PluralDisplayName:            "Workloads",
	IsPluginOriginated:           true,
	IsTargetRefBased:             false,
	HasToTargetRef:               false,
	HasFromTargetRef:             false,
	HasRulesTargetRef:            false,
	HasStatus:                    true,
	AllowedOnSystemNamespaceOnly: false,
	ShortName:                    "wl",
	IsFromAsRules:                false,
}
